/* =============================================
   FLORA.SYS · Green Gold Enterprises
   Catálogo Botánico 2026 — app.js
   ============================================= */

const CATS = {
  hierbas: { label: '🌿 HIERBAS', emoji: '🌿' },
  blends: { label: '☕ BLENDS', emoji: '☕' },
  especias: { label: '🌶 ESPECIAS', emoji: '🌶' },
  extractos: { label: '🧪 EXTRACTOS', emoji: '🧪' },
  frutas: { label: '🍌 FRUTAS', emoji: '🍌' },
  organicos: { label: '🌱 ORGÁNICOS', emoji: '🌱' },
  otros: { label: '📦 OTROS', emoji: '📦' },
};


const products = [
  /* ─── HIERBAS MEDICINALES Y AROMÁTICAS ─── */
  { id: 'H-001', cat: 'hierbas', name: 'Agaricus', sci: 'Agaricus blazei Murrill', desc: 'Propiedades inmunomoduladoras y antioxidantes destacadas. Empleado en suplementos de soporte inmunológico, salud oncológica complementaria y fortalecimiento de las defensas naturales.' },
  { id: 'H-002', cat: 'hierbas', name: 'Aguacatillo', sci: 'Persea americana Mill.', desc: 'Propiedades diuréticas y antiinflamatorias bien documentadas. Utilizada en formulaciones para el control del ácido úrico, soporte renal y bienestar articular.' },
  { id: 'H-003', cat: 'hierbas', name: 'Ajenjo', sci: 'Artemisia absinthium L.', desc: 'Acción digestiva, carminativa, colagoga y antiparasitaria. Componente de bitters, tónicos digestivos y formulaciones herbales.' },
  { id: 'H-004', cat: 'hierbas', name: 'Ajenjo póntico', sci: 'Artemisia pontica L.', desc: 'Propiedades digestivas y tónicas de perfil suave. Empleada en tónicos estomacales y preparaciones para estimular el apetito y la función digestiva.' },
  { id: 'H-005', cat: 'hierbas', name: 'Albahaca morada', sci: 'Ocimum basilicum L. var. purpurascens', desc: 'Variedad de albahaca con alto contenido en antocianinas y aceites esenciales. Utilizada en tés aromáticos, cosmética natural y suplementos antioxidantes.' },
  { id: 'H-006', cat: 'hierbas', name: 'Alcachofa (hojas)', sci: 'Cynara scolymus L.', desc: 'Propiedades hepatoprotectoras y coleréticas bien documentadas. Favorece la producción de bilis y el metabolismo lipídico; empleada en fórmulas detox, hepáticas y para el control del colesterol.' },
  { id: 'H-007', cat: 'hierbas', name: 'Alfalfa', sci: 'Medicago sativa L.', desc: 'Superalimento rico en proteínas, clorofila, vitaminas y minerales esenciales. Ingrediente estrella en suplementos nutricionales, mezclas verdes y formulaciones alcalinizantes.' },
  { id: 'H-008', cat: 'hierbas', name: 'Aloe del cabo', sci: 'Aloe ferox Mill.', desc: 'Látex del aloe ferox con potente efecto laxante y estimulante intestinal. Utilizado en fórmulas para el tránsito intestinal y programas detox; diferente del gel de aloe vera de uso cosmético.' },
  { id: 'H-009', cat: 'hierbas', name: 'Ambrette semilla', sci: 'Abelmoschus moschatus Medik.', desc: 'Semilla aromática con notas almizcladas naturales y suaves. Empleada en perfumería, cosmética y como sustituto natural del almizcle en formulaciones libres de origen animal.' },
  { id: 'H-010', cat: 'hierbas', name: 'Amor seco', sci: 'Bidens pilosa L.', desc: 'Propiedades antiinflamatorias, hepatoprotectoras y depurativas. Empleada en formulaciones para soporte hepático y manejo de la ictericia.' },
  { id: 'H-011', cat: 'hierbas', name: 'Anacardo (corteza)', sci: 'Anacardium occidentale L.', desc: 'Corteza del árbol de anacardo con propiedades antimicrobianas y astringentes bien documentadas. Utilizada en formulaciones para salud bucal, digestiva y cuidado de la piel.' },
  { id: 'H-012', cat: 'hierbas', name: 'Angélica', sci: 'Angelica archangelica L.', desc: 'Raíz con acción carminativa, espasmolítica y tónica digestiva. Componente de licores amargos, bitters y formulaciones herbales para el sistema digestivo.' },
  { id: 'H-013', cat: 'hierbas', name: 'Angélica (premium)', sci: 'Angelica archangelica L.', desc: 'Variedad premium con mayor concentración de cumarinas y aceites esenciales. Destinada a formulaciones especializadas, extractos estandarizados y aplicaciones nutracéuticas de alta gama.' },
  { id: 'H-014', cat: 'hierbas', name: 'Angélica semilla', sci: 'Angelica archangelica L.', desc: 'Semillas con aceite esencial de perfil fitoquímico diferenciado al de la raíz. Empleadas en destilación de aceites esenciales, licorería artesanal y formulaciones aromáticas especializadas.' },
  { id: 'H-015', cat: 'hierbas', name: 'Angico (corteza)', sci: 'Anadenanthera colubrina (Vell.) Brenan', desc: 'Corteza con propiedades antisépticas y expectorantes reconocidas. Aplicada en formulaciones para afecciones respiratorias, tos y bronquitis.' },
  { id: 'H-016', cat: 'hierbas', name: 'Árnica (flores)', sci: 'Arnica montana L.', desc: 'Potente acción antiinflamatoria y analgésica. Base de cremas, geles musculares y formulaciones para traumatismos y dolores musculoesqueléticos.' },
  { id: 'H-017', cat: 'hierbas', name: 'Árnica brasileña (solidago)', sci: 'Solidago microglossa D.C.', desc: 'Propiedades antiinflamatorias y analgésicas equiparables a la árnica europea. Empleada en extractos, tinturas y preparaciones herbales integrales.' },
  { id: 'H-018', cat: 'hierbas', name: 'Aroeira', sci: 'Schinus terebinthifolius Raddi.', desc: 'Potentes propiedades antisépticas, antiinflamatorias y cicatrizantes. Ampliamente usado en higiene íntima, salud ginecológica y productos de cuidado personal.' },
  { id: 'H-019', cat: 'hierbas', name: 'Artemisia', sci: 'Artemisia vulgaris L.', desc: 'Propiedades espasmolíticas, digestivas y antiparasitarias. Empleada en formulaciones para regulación menstrual, soporte digestivo y control de parásitos.' },
  { id: 'H-020', cat: 'hierbas', name: 'Assa-peixe', sci: 'Vernonanthura polyanthes (Spreng.) H.Rob.', desc: 'Propiedades expectorantes y broncodilatadoras ampliamente reconocidas. Referencia en formulaciones para salud respiratoria, tos y resfríos.' },
  { id: 'H-021', cat: 'hierbas', name: 'Balera', sci: 'Varronia curassavica Jacq.', desc: 'Potentes propiedades analgésicas y antiinflamatorias demostradas. Empleada en formulaciones tópicas para alivio de dolores musculares y articulares.' },
  { id: 'H-022', cat: 'hierbas', name: 'Banchá (hojas)', sci: 'Camellia sinensis (L.) Kuntze', desc: 'Variedad de té verde japonés de tercera y cuarta cosecha, naturalmente bajo en cafeína y rico en fluoruro. Ideal para tés funcionales, blends relajantes y formulaciones de salud bucal.' },
  { id: 'H-023', cat: 'hierbas', name: 'Barbatimán', sci: 'Stryphnodendron adstringens (Mart.) Coville', desc: 'Corteza con alto contenido en taninos condensados. Ampliamente utilizada en cosmética natural, higiene íntima femenina y formulaciones para mucosas y tejidos por sus propiedades astringentes y cicatrizantes.' },
  { id: 'H-024', cat: 'hierbas', name: 'Bardana (hojas)', sci: 'Arctium lappa L.', desc: 'Planta depurativa con propiedades diuréticas, antiinflamatorias y hepatoprotectoras. Empleada en formulaciones para salud de la piel, acné y tés de limpieza del organismo.' },
  { id: 'H-025', cat: 'hierbas', name: 'Benjuí', sci: 'Styrax benzoin Dryand.', desc: 'Resina aromática con propiedades antisépticas, expectorantes y fijadoras de fragancia natural. Empleada en cosmética, aromaterapia, inciensos y formulaciones para salud respiratoria.' },
  { id: 'H-026', cat: 'hierbas', name: 'Berro', sci: 'Nasturtium officinale R. Br.', desc: 'Planta rica en vitaminas C y K, hierro y antioxidantes naturales. Utilizada en suplementos depurativos, cápsulas nutricionales y mezclas verdes funcionales.' },
  { id: 'H-027', cat: 'hierbas', name: 'Boldo de Chile', sci: 'Peumus boldus Molina', desc: 'Hepatoprotector de amplio reconocimiento. Estimula la secreción biliar y la función digestiva; ingrediente clave en tés digestivos y formulaciones hepáticas.' },
  { id: 'H-028', cat: 'hierbas', name: 'Cabello de maíz (estigmas)', sci: 'Zea mays L.', desc: 'Estigmas del maíz con reconocida acción diurética y litolítica. Ingrediente clásico en tés y suplementos para soporte renal y control de la retención de líquidos.' },
  { id: 'H-029', cat: 'hierbas', name: 'Cálamo', sci: 'Acorus calamus L.', desc: 'Rizoma aromático con propiedades digestivas, carminativas y tónicas reconocidas. Empleado en licorería, formulaciones digestivas y como aromatizante en cosmética natural.' },
  { id: 'H-030', cat: 'hierbas', name: 'Caléndula (flores)', sci: 'Calendula officinalis L.', desc: 'Flores con sobresalientes propiedades antiinflamatorias, cicatrizantes y antisépticas. Ingrediente estrella en cosmética natural, cremas para pieles sensibles e irritadas y formulaciones dermatológicas.' },
  { id: 'H-031', cat: 'hierbas', name: 'Calumba', sci: 'Jateorhiza palmata (Lam.) Miers', desc: 'Raíz amarga con acción tónica gástrica y antidiarreica bien documentada. Utilizada en formulaciones digestivas y preparados amargos.' },
  { id: 'H-032', cat: 'hierbas', name: 'Camedrio', sci: 'Teucrium chamaedrys L.', desc: 'Hierba con propiedades tónicas, digestivas y levemente diuréticas. Empleada en formulaciones de apoyo hepático y digestivo en la herboristería clásica.' },
  { id: 'H-033', cat: 'hierbas', name: 'Canela de viejo (Ocotea)', sci: 'Ocotea odorifera (Vell.) Rohwer', desc: 'Propiedades antiinflamatorias y analgésicas validadas. Utilizada en formulaciones para dolores articulares, reumatismos y soporte del sistema musculoesquelético.' },
  { id: 'H-034', cat: 'hierbas', name: 'Carobinha', sci: 'Jacaranda caroba (Vell.) DC.', desc: 'Propiedades depurativas y dermatoprotectoras. Empleada en formulaciones naturales para el cuidado de la piel y tés depurativos.' },
  { id: 'H-035', cat: 'hierbas', name: 'Carqueja amarga', sci: 'Baccharis trimera (Less.) DC.', desc: 'Planta con potente acción digestiva, hepatoprotectora e hipoglucemiante. Ampliamente usada en suplementos para control glucémico, salud hepática y soporte del metabolismo.' },
  { id: 'H-036', cat: 'hierbas', name: 'Carqueja dulce', sci: 'Baccharis articulata (Lam.) Pers.', desc: 'Variedad de carqueja con propiedades digestivas y hepáticas de sabor más agradable. Ingrediente de tés y formulaciones para bienestar digestivo y hepático.' },
  { id: 'H-037', cat: 'hierbas', name: 'Cardo mariano', sci: 'Silybum marianum (L.) Gaertn.', desc: 'Semillas ricas en silimarina, potente hepatoprotector fitoquímico. Ingrediente clave en suplementos para salud hepática, detox y recuperación de la función del hígado.' },
  { id: 'H-038', cat: 'hierbas', name: 'Cardo santo', sci: 'Cnicus benedictus L.', desc: 'Propiedades tónicas, digestivas y galactogogas. Empleada en formulaciones para estimular la digestión y en tés de hierbas amargas.' },
  { id: 'H-039', cat: 'hierbas', name: 'Cáscara sagrada', sci: 'Rhamnus purshiana DC.', desc: 'Corteza con acción laxante suave y bien estudiada, basada en sus antraquinonas activas. Ingrediente estándar en suplementos para estreñimiento y regulación del tránsito intestinal.' },
  { id: 'H-040', cat: 'hierbas', name: 'Castaño de indias', sci: 'Aesculus hippocastanum L.', desc: 'Semilla rica en aescina con propiedades venotónicas y antiinflamatorias validadas clínicamente. Base de suplementos para insuficiencia venosa, varices y sensación de pesadez en piernas.' },
  { id: 'H-041', cat: 'hierbas', name: 'Catuaba (corteza)', sci: 'Erythroxylum catuaba Arr. Cam.', desc: 'Corteza con propiedades adaptógenas y tónicas reconocidas. Empleada en suplementos para energía, vitalidad sexual y soporte del sistema nervioso central.' },
  { id: 'H-042', cat: 'hierbas', name: 'Cedoaria', sci: 'Curcuma zedoaria (Christm.) Roscoe', desc: 'Rizoma aromático de la familia del jengibre con propiedades digestivas, antiinflamatorias y antimicrobianas. Empleada en formulaciones digestivas especializadas y cosmética natural.' },
  { id: 'H-043', cat: 'hierbas', name: 'Centáurea menor', sci: 'Centaurium erythraea Rafn.', desc: 'Propiedades tónicas digestivas y febrífugas. Empleada en formulaciones para estimular el apetito, la digestión y el soporte del hígado.' },
  { id: 'H-044', cat: 'hierbas', name: 'Centella asiática', sci: 'Centella asiatica (L.) Urb.', desc: 'Planta con reconocidas propiedades cicatrizantes, venotónicas y neuroprotectoras. Base de suplementos para circulación, salud de la piel, celulitis y función cognitiva.' },
  { id: 'H-045', cat: 'hierbas', name: 'Centella asiática (premium)', sci: 'Centella asiatica (L.) Urb.', desc: 'Variedad premium con mayor estandarización de asiaticósidos. Destinada a formulaciones nutracéuticas y cosméticas de alta gama donde se requiere máxima eficacia y trazabilidad.' },
  { id: 'H-046', cat: 'hierbas', name: 'Chancapiedra', sci: 'Phyllanthus niruri L.', desc: 'Planta con evidencia científica consolidada en el manejo de cálculos renales. Ampliamente empleada en suplementos para salud renal, disolución de piedras y bienestar urinario.' },
  { id: 'H-047', cat: 'hierbas', name: 'Cola de caballo', sci: 'Equisetum arvense L.', desc: 'Planta rica en sílice orgánico con propiedades diuréticas, remineralizantes y fortalecedoras del tejido conectivo. Clave en suplementos para cabello, piel, uñas y soporte renal.' },
  { id: 'H-048', cat: 'hierbas', name: 'Damiana', sci: 'Turnera diffusa Willd. ex Schult.', desc: 'Planta con propiedades tónicas, adaptógenas y afrodisíacas documentadas. Empleada en suplementos para vitalidad sexual, manejo del estrés y bienestar del sistema nervioso.' },
  { id: 'H-049', cat: 'hierbas', name: 'Diente de León', sci: 'Taraxacum officinale F.H. Wigg.', desc: 'Planta diurética y hepática con alta densidad nutricional. Empleada en programas detox, suplementos hepáticos, tés funcionales y como ingrediente en jugos y alimentos funcionales.' },
  { id: 'H-050', cat: 'hierbas', name: 'Douradinha', sci: 'Waltheria indica L.', desc: 'Propiedades diuréticas y de soporte renal documentadas. Empleada en formulaciones herbales para el manejo de edemas e infecciones del tracto urinario.' },
  { id: 'H-051', cat: 'hierbas', name: 'Emburana (corteza)', sci: 'Amburana cearensis (Allemão) A.C.Sm.', desc: 'Corteza con propiedades expectorantes y broncodilatadoras reconocidas. Empleada en formulaciones para afecciones respiratorias, bronquitis y tos.' },
  { id: 'H-052', cat: 'hierbas', name: 'Emburana (semilla)', sci: 'Amburana cearensis (Allemão) A.C. Sm.', desc: 'Semillas con propiedades antiespasmódicas y expectorantes de uso tradicional. Empleadas en formulaciones para salud bronquial y como apoyo en el tratamiento de enfermedades respiratorias.' },
  { id: 'H-053', cat: 'hierbas', name: 'Énula campana', sci: 'Inula helenium L.', desc: 'Raíz con inulina y propiedades expectorantes, antifúngicas y prebióticas. Empleada en suplementos para salud respiratoria y microbiota intestinal.' },
  { id: 'H-054', cat: 'hierbas', name: 'Equinácea', sci: 'Echinacea purpurea (L.) Moench', desc: 'Potente inmunoestimulante con amplia evidencia científica. Base de suplementos para prevención y manejo de resfríos, gripe y soporte del sistema inmune.' },
  { id: 'H-055', cat: 'hierbas', name: 'Escamonea', sci: 'Convolvulus scammonia L.', desc: 'Resina con potente acción laxante y purgante de uso especializado en fitoterapia. Requiere formulación técnica controlada con dosificación precisa.' },
  { id: 'H-056', cat: 'hierbas', name: 'Espinheira santa', sci: 'Maytenus ilicifolia Mart. ex Reissek', desc: 'Propiedades gastroprotectoras y antiulcerosas ampliamente validadas. Empleada en suplementos para gastritis, úlceras y soporte del tracto digestivo.' },
  { id: 'H-057', cat: 'hierbas', name: 'Espino blanco', sci: 'Crataegus monogyna Jacq.', desc: 'Fruto y flor con propiedades cardioprotectoras y antihipertensivas reconocidas científicamente. Ingrediente de referencia en suplementos para salud cardiovascular y control de la presión arterial.' },
  { id: 'H-058', cat: 'hierbas', name: 'Esponjilla del norte', sci: 'Luffa operculata (L.) Cogn.', desc: 'Planta con potente acción purgante y emética de uso especializado y controlado en fitoterapia. Requiere manejo técnico adecuado y formulación especializada.' },
  { id: 'H-059', cat: 'hierbas', name: 'Eucalipto globulus', sci: 'Eucalyptus globulus Labill.', desc: 'Planta con reconocida acción expectorante, antiséptica y broncodilatadora. Base de formulaciones para salud respiratoria, productos de aromaterapia e higiene natural.' },
  { id: 'H-060', cat: 'hierbas', name: 'Frangula (arraclán)', sci: 'Frangula alnus Mill.', desc: 'Corteza con suave acción laxante de tipo antraquinónico. Alternativa bien tolerada a la cáscara sagrada para formulaciones de estreñimiento y regulación intestinal.' },
  { id: 'H-061', cat: 'hierbas', name: 'Fucus vesiculosus', sci: 'Fucus vesiculosus L.', desc: 'Rica en yodo orgánico, minerales y fucoidanos bioactivos. Empleada en suplementos para el control de peso y soporte tiroideo.' },
  { id: 'H-062', cat: 'hierbas', name: 'Galanga', sci: 'Alpinia galanga (L.) Willd.', desc: 'Rizoma aromático de la familia del jengibre con propiedades digestivas, antiinflamatorias y antimicrobianas. Empleado en condimentos, tés funcionales y formulaciones herbales especializadas.' },
  { id: 'H-063', cat: 'hierbas', name: 'Garcinia (fruto)', sci: 'Garcinia cambogia (Gaertn.) Desr.', desc: 'Fuente natural de ácido hidroxicítrico (HCA) con propiedades para el manejo del peso. Ampliamente empleada en suplementos para el control del apetito, metabolismo lipídico y composición corporal.' },
  { id: 'H-064', cat: 'hierbas', name: 'Garra del diablo', sci: 'Harpagophytum procumbens DC.', desc: 'Raíz con potente actividad antiinflamatoria y analgésica validada en estudios clínicos. Base de suplementos para dolor articular, artritis y soporte musculoesquelético.' },
  { id: 'H-065', cat: 'hierbas', name: 'Gayuba', sci: 'Arctostaphylos uva-ursi (L.) Spreng.', desc: 'Hojas con arbutina e hidroquinona con reconocida acción antiséptica urinaria. Ingrediente clave en suplementos para infecciones del tracto urinario y cistitis recurrente.' },
  { id: 'H-066', cat: 'hierbas', name: 'Genciana', sci: 'Gentiana lutea L.', desc: 'Raíz amarga con potente acción tónica digestiva. Ingrediente en bitters, aperitivos herbales y formulaciones para estimular el apetito y optimizar la digestión.' },
  { id: 'H-067', cat: 'hierbas', name: 'Ginkgo biloba', sci: 'Ginkgo biloba L.', desc: 'Amplia evidencia científica en neuroprotección y mejora de la circulación periférica y cerebral. Ingrediente clave en suplementos para memoria, concentración y salud cognitiva.' },
  { id: 'H-068', cat: 'hierbas', name: 'Ginseng brasileño', sci: 'Pfaffia paniculata (Mart.) Kuntze', desc: 'Raíz de Pfaffia paniculata con propiedades adaptógenas para energía, resistencia al estrés y vitalidad física y mental. Empleada en suplementos para rendimiento físico y cognitivo.' },
  { id: 'H-069', cat: 'hierbas', name: 'Ginseng panax', sci: 'Panax ginseng C.A. Mey.', desc: 'Adaptógeno con amplia evidencia científica acumulada. Base de suplementos para energía, inmunidad, función sexual y rendimiento cognitivo.' },
  { id: 'H-070', cat: 'hierbas', name: 'Granada', sci: 'Punica granatum L.', desc: 'Fruta rica en polifenoles, elagitaninos y antocianinas con propiedades antioxidantes, cardiovasculares y antiinflamatorias. Ingrediente premium en suplementos de alto valor y alimentos funcionales.' },
  { id: 'H-071', cat: 'hierbas', name: 'Grindelia', sci: 'Grindelia robusta Nutt.', desc: 'Planta con propiedades expectorantes y broncodilatadoras reconocidas en fitoterapia. Empleada en formulaciones para asma, bronquitis y afecciones de las vías respiratorias superiores.' },
  { id: 'H-072', cat: 'hierbas', name: 'Guaco', sci: 'Mikania glomerata Spreng.', desc: 'Propiedades broncodilatadoras y antiinflamatorias respiratorias ampliamente reconocidas. Ingrediente de jarabes, suplementos y formulaciones para asma y tos.' },
  { id: 'H-073', cat: 'hierbas', name: 'Guanábana', sci: 'Annona muricata L.', desc: 'Fruta tropical con alto contenido en acetogeninas de propiedades inmunomoduladoras en investigación. Empleada en suplementos para soporte inmunológico y formulaciones oncológicas complementarias.' },
  { id: 'H-074', cat: 'hierbas', name: 'Guaraná (granos)', sci: 'Paullinia cupana Kunth', desc: 'Semillas con muy alta concentración natural de cafeína. Base de energizantes, suplementos termogénicos y formulaciones para rendimiento físico y concentración mental.' },
  { id: 'H-075', cat: 'hierbas', name: 'Hamamelis (hojas)', sci: 'Hamamelis virginiana L.', desc: 'Planta con alto contenido en taninos y reconocidas propiedades astringentes, venotónicas y antiinflamatorias. Base de cosméticos para pieles sensibles, irritadas y tratamientos para várices.' },
  { id: 'H-076', cat: 'hierbas', name: 'Hibiscus', sci: 'Hibiscus sabdariffa L.', desc: 'Flor con propiedades antihipertensivas, diuréticas y antioxidantes ampliamente documentadas. Ingrediente estrella en tés funcionales, bebidas naturales y suplementos para el control de la presión arterial.' },
  { id: 'H-077', cat: 'hierbas', name: 'Hierba de bicho', sci: 'Persicaria punctata (Elliott) Small', desc: 'Planta con propiedades antiinflamatorias, hemostáticas y flebotónicas. Empleada en formulaciones anorrectales para el manejo de hemorroides y el soporte venoso.' },
  { id: 'H-078', cat: 'hierbas', name: 'Hierba luisa', sci: 'Cymbopogon citratus (DC.) Stapf', desc: 'Planta aromática con potente aroma cítrico y propiedades calmantes, digestivas y antibacterianas. Ampliamente empleada en tés funcionales, cosmética natural y como aroma natural para alimentos.' },
  { id: 'H-079', cat: 'hierbas', name: 'Hipérico (hierba de San Juan)', sci: 'Hypericum perforatum L.', desc: 'Planta con amplia evidencia clínica en el manejo de depresión leve a moderada. Base de suplementos para el equilibrio del estado de ánimo y el bienestar emocional.' },
  { id: 'H-080', cat: 'hierbas', name: 'Hipérico (extracto)', sci: 'Hypericum perforatum L.', desc: 'Extracto estandarizado en hipericina con potente actividad antidepresiva. Mayor potencia y precisión de dosis para el soporte del equilibrio emocional.' },
  { id: 'H-081', cat: 'hierbas', name: 'Jaborandi', sci: 'Pilocarpus microphyllus Stapf ex Wardleworth', desc: 'Planta con alto contenido en pilocarpina, alcaloide utilizado en oftalmología para el tratamiento del glaucoma y la estimulación de glándulas secretoras. Empleada también en cosmética capilar.' },
  { id: 'H-082', cat: 'hierbas', name: 'Jalapa', sci: 'Ipomoea purga (Wender.) Hayne', desc: 'Raíz con potente acción purgante de uso especializado y controlado en formulaciones fitoterapéuticas. Requiere manejo técnico adecuado y formulación profesional.' },
  { id: 'H-083', cat: 'hierbas', name: 'Jambul', sci: 'Syzygium cumini (L.) Skeels', desc: 'Fruto con propiedades hipoglucemiantes y astringentes documentadas. Ingrediente en suplementos para el control de glucosa en sangre y soporte complementario en el manejo de la diabetes tipo 2.' },
  { id: 'H-084', cat: 'hierbas', name: 'Jazmín (flores)', sci: 'Jasminum officinale L.', desc: 'Flores con propiedades calmantes, afrodisíacas y aromáticas de alta calidad sensorial. Empleadas en tés premium, aromaterapia, cosmética natural y formulaciones para el manejo del estrés.' },
  { id: 'H-085', cat: 'hierbas', name: 'Jatobá (corteza)', sci: 'Hymenaea courbaril L.', desc: 'Corteza con propiedades antifúngicas, energizantes y expectorantes reconocidas. Empleada en formulaciones para candidiasis, salud de las vías respiratorias y suplementos de vitalidad.' },
  { id: 'H-086', cat: 'hierbas', name: 'Juá (corteza)', sci: 'Ziziphus joazeiro Mart.', desc: 'Corteza con propiedades astringentes y antisépticas de especial utilidad en higiene oral. Empleada en dentífricos naturales, enjuagues bucales y formulaciones para salud bucal.' },
  { id: 'H-087', cat: 'hierbas', name: 'Junco de laguna (hojas)', sci: 'Typha domingensis Pers.', desc: 'Planta acuática con propiedades diuréticas y depurativas documentadas. Empleada en formulaciones herbales para el soporte renal y mezclas de plantas para el control de peso.' },
  { id: 'H-088', cat: 'hierbas', name: 'Jurubeba (planta)', sci: 'Solanum paniculatum L.', desc: 'Propiedades hepáticas, digestivas y antianémicas de larga tradición. Empleada en tónicos para hígado, bazo y soporte de la función digestiva.' },
  { id: 'H-089', cat: 'hierbas', name: 'Jurubeba (raíz)', sci: 'Solanum paniculatum L.', desc: 'Raíz con mayor concentración de principios activos hepatoprotectores que la parte aérea. Preferida para extractos y formulaciones hepáticas de alta potencia y biodisponibilidad.' },
  { id: 'H-090', cat: 'hierbas', name: 'Lapacho morado (corteza)', sci: 'Handroanthus impetiginosus (Mart. ex DC.) Mattos', desc: 'Corteza con propiedades antifúngicas, antiparasitarias e inmunomoduladoras reconocidas. Empleada en formulaciones para candidiasis, soporte inmunológico y salud intestinal.' },
  { id: 'H-091', cat: 'hierbas', name: 'Lavanda azul', sci: 'Lavandula angustifolia Mill.', desc: 'Planta de reconocida acción calmante y ansiolítica. Base de formulaciones para manejo del estrés, mejora de la calidad del sueño y productos de aromaterapia y cosmética natural.' },
  { id: 'H-092', cat: 'hierbas', name: 'Lavanda súper azul', sci: 'Lavandula angustifolia Mill.', desc: 'Variedad seleccionada de lavanda con mayor concentración de linalool. Preferida para aplicaciones de gama alta en aromaterapia, cosmética premium y suplementos relajantes.' },
  { id: 'H-093', cat: 'hierbas', name: 'Limón (corteza)', sci: 'Citrus limon (L.) Osbeck', desc: 'Cáscara rica en flavonoides, limoneno y aceites esenciales de alto valor funcional. Empleada en tés digestivos, suplementos antioxidantes, cosmética natural y como aromatizante de origen natural.' },
  { id: 'H-094', cat: 'hierbas', name: 'Lirio florentino', sci: 'Iris × germanica L.', desc: 'Rizoma de iris con fragancia característica y persistente. Empleado en perfumería de alta gama como fijador natural, en cosmética premium y formulaciones aromáticas especializadas.' },
  { id: 'H-095', cat: 'hierbas', name: 'Llantén', sci: 'Plantago major L.', desc: 'Planta con propiedades expectorantes, emolientes y antiinflamatorias bien documentadas. Ampliamente empleada en tés para vías respiratorias, formulaciones para tos y como digestivo suave.' },
  { id: 'H-096', cat: 'hierbas', name: 'Lúpulo (flores)', sci: 'Humulus lupulus L.', desc: 'Estróbilos con propiedades sedantes y ansiolíticas ampliamente utilizadas. Ingrediente clave en formulaciones para el sueño, manejo del estrés y en la industria cervecera artesanal.' },
  { id: 'H-097', cat: 'hierbas', name: 'Macela (manzanilla del campo)', sci: 'Achyrocline satureioides (Lam.) DC.', desc: 'Propiedades antiinflamatorias y digestivas similares a la manzanilla europea. Empleada en tés y suplementos de probada eficacia.' },
  { id: 'H-098', cat: 'hierbas', name: 'Malva', sci: 'Malva sylvestris L.', desc: 'Planta con propiedades emolientes, antiinflamatorias y expectorantes suaves. Ampliamente empleada en tés, jarabes y formulaciones para mucosas y vías respiratorias.' },
  { id: 'H-099', cat: 'hierbas', name: 'Malva (premium)', sci: 'Malva sylvestris L.', desc: 'Variedad premium con mayor concentración de mucílagos activos. Ideal para formulaciones que requieren mayor efecto emoliente y antiinflamatorio sobre mucosas y piel.' },
  { id: 'H-100', cat: 'hierbas', name: 'Manzanilla (flores)', sci: 'Matricaria chamomilla L.', desc: 'Propiedades antiinflamatorias, espasmolíticas y sedantes suaves. Ingrediente universal en tés, suplementos y cosmética.' },
  { id: 'H-101', cat: 'hierbas', name: 'Maracuyá (hojas)', sci: 'Passiflora edulis Sims', desc: 'Hojas con potentes propiedades ansiolíticas y sedantes reconocidas en fitoterapia científica. Empleadas en formulaciones para ansiedad, insomnio y estrés emocional.' },
  { id: 'H-102', cat: 'hierbas', name: 'Matcha polvo soluble', sci: 'Camellia sinensis (L.) Kuntze', desc: 'Té verde japonés en polvo de alta biodisponibilidad con alto contenido en EGCG y L-teanina. Preferido en bebidas funcionales premium, suplementos antioxidantes y alimentos funcionales de alta gama.' },
  { id: 'H-103', cat: 'hierbas', name: 'Mate tostado', sci: 'Ilex paraguariensis A.St.-Hil.', desc: 'Yerba mate con perfil de sabor tostado y menor astringencia. Empleado en infusiones, blends energizantes y como base de bebidas funcionales.' },
  { id: 'H-104', cat: 'hierbas', name: 'Mate verde', sci: 'Ilex paraguariensis A.St.-Hil.', desc: 'Yerba mate sin tostar con mayor contenido en clorofila y antioxidantes. Base de bebidas energizantes naturales, suplementos y formulaciones para rendimiento y control de peso.' },
  { id: 'H-105', cat: 'hierbas', name: 'Melisa (Melissa officinalis)', sci: 'Melissa officinalis L.', desc: 'Variedad estándar de melissa con mayor estandarización de ácido rosmarínico. Preferida para formulaciones nutracéuticas, extractos y suplementos de alta gama.' },
  { id: 'H-106', cat: 'hierbas', name: 'Melón amargo', sci: 'Momordica charantia L.', desc: 'Planta con propiedades hipoglucemiantes e hipocolesterolemiantes documentadas. Empleada en formulaciones para el control de glucosa y colesterol en fitoterapia integrativa.' },
  { id: 'H-107', cat: 'hierbas', name: 'Menta', sci: 'Mentha × piperita L.', desc: 'Propiedades digestivas, refrescantes y analgésicas. Ingrediente universal en tés, higiene oral, cosmética y alimentos funcionales.' },
  { id: 'H-108', cat: 'hierbas', name: 'Milenrama', sci: 'Achillea millefolium L.', desc: 'Planta con acción antiinflamatoria, hemostática y tónica venosa bien documentadas. Empleada en formulaciones para circulación, cicatrización y tés de bienestar general.' },
  { id: 'H-109', cat: 'hierbas', name: 'Mil hombres (aristoloquia)', sci: 'Aristolochia cymbifera Mart. & Zucc.', desc: '⚠️ ADVERTENCIA REGULATORIA: Contiene ácidos aristolóquicos con nefrotoxicidad y potencial carcinogénico documentados. Comercialización prohibida o severamente restringida en UE, EE.UU., Canadá y otros mercados. No recomendado sin evaluación legal y toxicológica previa.', warning: true },
  { id: 'H-110', cat: 'hierbas', name: 'Mora hojas', sci: 'Morus nigra L.', desc: 'Hojas con propiedades hipoglucemiantes y antioxidantes documentadas. Empleadas en tés funcionales para el control glucémico y formulaciones de soporte metabólico.' },
  { id: 'H-111', cat: 'hierbas', name: 'Muirapuama', sci: 'Ptychopetalum olacoides Benth.', desc: 'Propiedades afrodisíacas y tónicas nerviosas ampliamente documentadas. Base de suplementos para vitalidad sexual, rendimiento y soporte del sistema nervioso.' },
  { id: 'H-112', cat: 'hierbas', name: 'Mulungu', sci: 'Erythrina mulungu Mart. ex Benth.', desc: 'Potentes propiedades sedantes y ansiolíticas. Base de suplementos naturales para ansiedad, insomnio y equilibrio del sistema nervioso.' },
  { id: 'H-113', cat: 'hierbas', name: 'Naranja (corteza amarga)', sci: 'Citrus aurantium L.', desc: 'Fuente de sinefrina con propiedades termogénicas y lipolíticas. Ingrediente clave en suplementos para control de peso, quema de grasa y rendimiento deportivo.' },
  { id: 'H-114', cat: 'hierbas', name: 'Naranja (corteza dulce)', sci: 'Citrus sinensis (L.) Osbeck', desc: 'Corteza aromática con aceites esenciales y flavonoides bioactivos. Empleada en tés digestivos, cosmética, aromaterapia y como saborizante natural en alimentos y bebidas funcionales.' },
  { id: 'H-115', cat: 'hierbas', name: 'Nuez de cola', sci: 'Cola nitida (Vent.) Schott & Endl.', desc: 'Semilla rica en cafeína y teobromina con propiedades estimulantes reconocidas. Ingrediente en energizantes, suplementos para rendimiento físico y mental y bebidas funcionales.' },
  { id: 'H-116', cat: 'hierbas', name: 'Nudo de perro', sci: 'Petrea volubilis L.', desc: 'Propiedades analgésicas y antiinflamatorias para uso externo e interno. Empleada en formulaciones para dolores reumáticos y musculares.' },
  { id: 'H-117', cat: 'hierbas', name: 'Olivo', sci: 'Olea europaea L.', desc: 'Hojas ricas en oleuropeína con propiedades antihipertensivas, antioxidantes y antimicrobianas. Ingrediente de referencia en suplementos cardiovasculares y formulaciones para la presión arterial.' },
  { id: 'H-118', cat: 'hierbas', name: 'Ora pro nóbis', sci: 'Pereskia aculeata Mill.', desc: 'Notable contenido proteico, mucílagos y hierro de origen vegetal. Empleada en suplementos nutricionales, alimentos funcionales y formulaciones para salud de la piel.' },
  { id: 'H-119', cat: 'hierbas', name: 'Ortiga', sci: 'Urtica dioica L.', desc: 'Planta rica en hierro, vitaminas y minerales con propiedades diuréticas y antiinflamatorias. Empleada en suplementos nutritivos, formulaciones para alergias y soporte de la salud prostática.' },
  { id: 'H-120', cat: 'hierbas', name: 'Paico', sci: 'Dysphania ambrosioides (L.) Mosyakin & Clemants', desc: 'Planta con conocidas propiedades antiparasitarias y carminativas. Empleada en formulaciones para el control de parásitos intestinales y el bienestar digestivo.' },
  { id: 'H-121', cat: 'hierbas', name: 'Paico (planta entera)', sci: 'Dysphania ambrosioides (L.) Mosyakin & Clemants', desc: 'Propiedades expectorantes, digestivas y antiparasitarias. Empleada en formulaciones para salud respiratoria y bienestar digestivo.' },
  { id: 'H-122', cat: 'hierbas', name: 'Paratudo', sci: 'Lychnophora ericoides Mart.', desc: 'Propiedades digestivas, antiinflamatorias y tónicas. Empleada en formulaciones herbales para bienestar general.' },
  { id: 'H-123', cat: 'hierbas', name: 'Pariparoba', sci: 'Piper umbellatum L.', desc: 'Propiedades antiinflamatorias, analgésicas y de soporte hepático. Empleada en formulaciones fitoterapéuticas.' },
  { id: 'H-124', cat: 'hierbas', name: 'Pasiflora', sci: 'Passiflora incarnata L.', desc: 'Potentes propiedades ansiolíticas y sedantes con amplia evidencia científica. Ingrediente clave en formulaciones para ansiedad, insomnio y estrés, sin efectos adictivos.' },
  { id: 'H-125', cat: 'hierbas', name: 'Pata de vaca', sci: 'Bauhinia forficata Link', desc: 'Planta con propiedades hipoglucemiantes documentadas en estudios clínicos. Ampliamente empleada en suplementos para el control de glucosa en sangre y soporte complementario en diabetes.' },
  { id: 'H-126', cat: 'hierbas', name: 'Pau pereira', sci: 'Geissospermum vellosii Allemão', desc: 'Corteza con propiedades antiparasitarias, antivirales e inmunomoduladoras. Empleada en formulaciones para soporte inmunológico y en investigación oncológica complementaria.' },
  { id: 'H-127', cat: 'hierbas', name: 'Pau tenente', sci: 'Zanthoxylum rhoifolium Lam.', desc: 'Propiedades antiinflamatorias y antimicrobianas reconocidas. Empleada en formulaciones para afecciones de piel e infecciones.' },
  { id: 'H-128', cat: 'hierbas', name: 'Petiveria', sci: 'Petiveria alliacea L.', desc: 'Propiedades antiinflamatorias, analgésicas y antimicrobianas documentadas. Empleada en formulaciones para diversas afecciones.' },
  { id: 'H-129', cat: 'hierbas', name: 'Pfaffia', sci: 'Pfaffia paniculata (Mart.) Kuntze', desc: 'Parte aérea de Pfaffia paniculata diferenciada del extracto de raíz. Contiene beta-ecdisterona y fitosteroles con propiedades para equilibrio hormonal, vitalidad sexual y resistencia al estrés.' },
  { id: 'H-130', cat: 'hierbas', name: 'Piedra hume', sci: 'Caesalpinia ferrea Mart.', desc: 'Propiedades astringentes, antisépticas y cicatrizantes. Empleado en formulaciones cosméticas, productos aftershave y cuidado de la piel.' },
  { id: 'H-131', cat: 'hierbas', name: 'Poleo', sci: 'Mentha pulegium L.', desc: 'Especie de menta con potente acción digestiva, carminativa y expectorante. Empleada en tés y formulaciones digestivas; su formulación requiere control de dosis por contenido en pulegona.' },
  { id: 'H-132', cat: 'hierbas', name: 'Porangaba', sci: 'Cordia ecalyculata Vell.', desc: 'Propiedades diuréticas y para el control de peso documentadas. Empleada en suplementos termogénicos y fórmulas para adelgazar.' },
  { id: 'H-133', cat: 'hierbas', name: 'Quina calisaya', sci: 'Cinchona calisaya Wedd.', desc: 'Corteza con alto contenido en quinina y alcaloides de propiedades tónicas y antifebriles. Empleada en formulaciones tónicas, aperitivas y en la industria de bebidas como base de tónicos amargos.' },
  { id: 'H-134', cat: 'hierbas', name: 'Quina quina', sci: 'Cinchona officinalis L.', desc: 'Corteza amarga con propiedades tónicas, febrífugas y digestivas de larga tradición. Componente de fórmulas herbales, bitters y tónicos.' },
  { id: 'H-135', cat: 'hierbas', name: 'Quina roja', sci: 'Cinchona pubescens Vahl', desc: 'Corteza de cinchona con propiedades antifebriles, digestivas y tónicas. Empleada en formulaciones herbales, licorería de especialidad y tónicos amargos.' },
  { id: 'H-136', cat: 'hierbas', name: 'Regaliz', sci: 'Glycyrrhiza glabra L.', desc: 'Variedad premium de regaliz con mayor estandarización en glicirrizina. Preferida para formulaciones farmacéuticas y nutracéuticas que requieren alta trazabilidad y calidad.' },
  { id: 'H-137', cat: 'hierbas', name: 'Regaliz brasileiro', sci: 'Periandra mediterranea (Vell.) Taub.', desc: 'Raíz con potentes propiedades antiinflamatorias, expectorantes y gastroprotectoras. Ingrediente de tradición en formulaciones para salud gástrica, tos y bienestar general.' },
  { id: 'H-138', cat: 'hierbas', name: 'Roble (corteza)', sci: 'Quercus robur L.', desc: 'Corteza rica en taninos con propiedades astringentes y antiinflamatorias. Empleada en formulaciones para mucosas, higiene oral, diarrea y cuidado externo de la piel.' },
  { id: 'H-139', cat: 'hierbas', name: 'Roble (madera)', sci: 'Quercus robur L.', desc: 'Madera con propiedades astringentes y aromatizantes de uso tradicional. Empleada en infusiones, extractos y como componente de formulaciones herbales y licorería artesanal.' },
  { id: 'H-140', cat: 'hierbas', name: 'Rosa mosqueta', sci: 'Rosa canina L.', desc: 'Fruto con muy alto contenido natural de vitamina C y antioxidantes. Ingrediente en suplementos inmunitarios, cosméticos antienvejecimiento y formulaciones antioxidantes.' },
  { id: 'H-141', cat: 'hierbas', name: 'Rosa roja', sci: 'Rosa × damascena Mill.', desc: 'Pétalos con propiedades antioxidantes, aromáticas y astringentes suaves. Empleados en cosmética natural, tés premium, aromaterapia y formulaciones de bienestar femenino.' },
  { id: 'H-142', cat: 'hierbas', name: 'Ruda', sci: 'Ruta graveolens L.', desc: 'Propiedades espasmolíticas y reguladoras. Empleada en formulaciones para regularidad menstrual y soporte del sistema nervioso.' },
  { id: 'H-143', cat: 'hierbas', name: 'Ruibarbo', sci: 'Rheum rhabarbarum L.', desc: 'Rizoma con propiedades laxantes de acción antraquinónica y efecto astringente complementario. Empleado en formulaciones para el tránsito intestinal y como ingrediente en licorería y alimentación funcional.' },
  { id: 'H-144', cat: 'hierbas', name: 'Salvia', sci: 'Salvia officinalis L.', desc: 'Planta con propiedades antisudorales, antiinflamatorias y estrogénicas suaves documentadas. Base de formulaciones para menopausia, sudoración excesiva e higiene oral.' },
  { id: 'H-145', cat: 'hierbas', name: 'Salvia esclarea', sci: 'Salvia sclarea L.', desc: 'Variedad de salvia con alta concentración de aceite esencial de linalool acetato. Empleada en aromaterapia, cosmética y formulaciones para bienestar hormonal femenino.' },
  { id: 'H-146', cat: 'hierbas', name: 'Sasafrás (madera)', sci: 'Ocotea cymbarum Kunth', desc: '⚠️ Su principio activo safrol está clasificado como posible carcinógeno (IARC Grupo 2B). Uso prohibido en alimentos por FDA y UE; con restricciones en cosmética. Consulte normativa vigente en su mercado.', warning: true },
  { id: 'H-147', cat: 'hierbas', name: 'Sauce blanco', sci: 'Salix alba L.', desc: 'Corteza con salicina, el precursor natural del ácido acetilsalicílico. Ingrediente en suplementos para el dolor, fiebre e inflamación con acción suave y perfil de seguridad favorable.' },
  { id: 'H-148', cat: 'hierbas', name: 'Saúco', sci: 'Sambucus nigra L.', desc: 'Flor y fruto con propiedades antivirales, diaforéticas e inmunoestimulantes reconocidas. Ampliamente empleados en suplementos para resfríos, gripe e inmunidad estacional.' },
  { id: 'H-149', cat: 'hierbas', name: 'Saw palmetto', sci: 'Serenoa repens (Bartram) Small', desc: 'Baya con amplia evidencia clínica para el soporte de la salud prostática. Ingrediente clave en suplementos para salud masculina, hiperplasia prostática benigna y vitalidad.' },
  { id: 'H-150', cat: 'hierbas', name: 'Semilla tonka', sci: 'Dipteryx odorata (Aubl.) Willd.', desc: 'Semilla aromática con alto contenido en cumarina y fragancia intensa y característica. Empleada en perfumería, cosmética, tabaco y alimentos gourmet.' },
  { id: 'H-151', cat: 'hierbas', name: 'Sen (folículos)', sci: 'Senna alexandrina Mill.', desc: 'Frutos de sena con acción laxante más suave que las hojas. Opción preferida para formulaciones que requieren menor intensidad de efecto o para poblaciones sensibles.' },
  { id: 'H-152', cat: 'hierbas', name: 'Sen (hojas)', sci: 'Senna alexandrina Mill.', desc: 'Hojas con potente y reconocida acción laxante de tipo antraquinónico. Ingrediente estándar en suplementos para estreñimiento y preparación intestinal pre-procedimiento.' },
  { id: 'H-153', cat: 'hierbas', name: 'Siete sangrías', sci: 'Cuphea carthagenensis (Jacq.) J.F. Macbr.', desc: 'Propiedades diuréticas y depurativas. Empleada en formulaciones para el soporte renal, limpieza del organismo y control de la presión arterial.' },
  { id: 'H-154', cat: 'hierbas', name: 'Sombrero de cuero', sci: 'Echinodorus grandiflorus (Cham. & Schltdl.) Micheli', desc: 'Propiedades antiinflamatorias y diuréticas documentadas. Empleada en formulaciones para soporte renal y articular.' },
  { id: 'H-155', cat: 'hierbas', name: 'Stevia', sci: 'Stevia rebaudiana (Bertoni) Bertoni', desc: 'Edulcorante natural sin calorías, hasta 300 veces más dulce que el azúcar. Ingrediente fundamental en bebidas, alimentos y suplementos para el control glucémico y la gestión del peso.' },
  { id: 'H-156', cat: 'hierbas', name: 'Sucupira (corteza)', sci: 'Pterodon pubescens (Benth.) Benth.', desc: 'Corteza con propiedades antiinflamatorias y analgésicas para uso articular. Empleada en suplementos para artritis, reumatismos y soporte musculoesquelético.' },
  { id: 'H-157', cat: 'hierbas', name: 'Sucupira (semilla)', sci: 'Pterodon pubescens (Benth.) Benth.', desc: 'Semillas con mayor concentración de principios activos antiinflamatorios que la corteza. Preferidas para extractos y formulaciones articulares de alta potencia y biodisponibilidad.' },
  { id: 'H-158', cat: 'hierbas', name: 'Taiuia', sci: 'Cayaponia tayuya (Vell.) Cogn.', desc: 'Propiedades antiinflamatorias y de soporte hepático. Empleada en formulaciones para bienestar digestivo y hepático.' },
  { id: 'H-159', cat: 'hierbas', name: 'Té blanco', sci: 'Camellia sinensis (L.) Kuntze', desc: 'Té mínimamente procesado, excepcionalmente rico en catequinas y antioxidantes. Apreciado en formulaciones premium antienvejecimiento, suplementos antioxidantes y mezclas de tés gourmet.' },
  { id: 'H-160', cat: 'hierbas', name: 'Té de bugre', sci: 'Cordia ecalyculata Vell.', desc: 'Propiedades diuréticas, cardiotónicas y para el control de peso. Ingrediente en suplementos termogénicos y fórmulas para adelgazar.' },
  { id: 'H-161', cat: 'hierbas', name: 'Té negro', sci: 'Camellia sinensis (L.) Kuntze', desc: 'Té fermentado rico en teaflavinas y theína con propiedades antioxidantes. Empleado en blends energizantes, formulaciones antioxidantes y como base de kombucha y bebidas fermentadas.' },
  { id: 'H-162', cat: 'hierbas', name: 'Té verde', sci: 'Camellia sinensis (L.) Kuntze', desc: 'Camellia sinensis con perfil estandarizado de EGCG para suplementos antioxidantes, termogénicos y formulaciones funcionales de alto valor nutracéutico.' },
  { id: 'H-163', cat: 'hierbas', name: 'Té verde (producción local)', sci: 'Camellia sinensis (L.) Kuntze', desc: 'Té verde con buen perfil de polifenoles y antioxidantes. Adecuado para tés, blends funcionales y suplementos nutracéuticos.' },
  { id: 'H-164', cat: 'hierbas', name: 'Té verde premium', sci: 'Camellia sinensis (L.) Kuntze', desc: 'Selección de primera calidad de hojas de Camellia sinensis. Perfil organoléptico superior; ideal para marcas propias de tés gourmet y suplementos premium de alto valor.' },
  { id: 'H-165', cat: 'hierbas', name: 'Tilo', sci: 'Tilia cordata Mill.', desc: 'Flor con acción sedante, antiespasmódica y diaforética suave de probada eficacia. Ingrediente clásico en tés para el estrés, el sueño y la relajación; apto para todas las edades.' },
  { id: 'H-166', cat: 'hierbas', name: 'Toronjil', sci: 'Melissa officinalis L.', desc: 'Melissa de producción local con propiedades calmantes, carminativas y antivirales. Ingrediente de tés para el estrés, el sueño reparador y el bienestar digestivo.' },
  { id: 'H-167', cat: 'hierbas', name: 'Uña de gato', sci: 'Uncaria tomentosa (Willd.) DC.', desc: 'Corteza con propiedades inmunomoduladoras y antiinflamatorias ampliamente estudiadas. Base de suplementos para inmunidad, artritis y bienestar general.' },
  { id: 'H-168', cat: 'hierbas', name: 'Uxi amarillo', sci: 'Endopleura uchi (Huber) Cuatrec.', desc: 'Propiedades antiinflamatorias y de soporte hormonal femenino. Empleado en formulaciones para quistes ováricos y bienestar ginecológico.' },
  { id: 'H-169', cat: 'hierbas', name: 'Vainilla', sci: 'Vanilla planifolia Andrews', desc: 'Especia de alto valor aromático y antioxidante. Ingrediente premium en alimentación funcional, cosmética natural y formulaciones de bienestar.' },
  { id: 'H-170', cat: 'hierbas', name: 'Valeriana (raíz)', sci: 'Valeriana officinalis L.', desc: 'Raíz con amplia evidencia clínica en el manejo del insomnio y la ansiedad. Ingrediente clásico en suplementos para el sueño, el estrés y la relajación del sistema nervioso.' },
  { id: 'H-171', cat: 'hierbas', name: 'Zarzaparrilla', sci: 'Smilax regelii Killip & C.V. Morton', desc: 'Raíz con propiedades depurativas, antiinflamatorias y adaptógenas reconocidas. Empleada en suplementos para articulaciones, salud de la piel, energía masculina y formulaciones depurativas de sangre.' },

  /* ─── BLENDS / TÉS MIXTOS ─── */
  { id: 'B-001', img: '2_Blends_tes_mixtos/Te_caliente.jpeg', cat: 'blends', name: 'Té caliente (quentão)', sci: 'Mezcla de especias', desc: 'Mezcla de especias cálidas con jengibre, canela, clavo y otras especias; ideal para productos estacionales y marcas propias.' },
  { id: 'B-002', img: '2_Blends_tes_mixtos/Te_flores_frutas.jpeg', cat: 'blends', name: 'Té de flores y frutas', sci: 'Blend botánico', desc: 'Mezcla de pétalos y frutas deshidratadas de alta calidad sensorial. Perfil aromático y visual atractivo, ideal para líneas gourmet y tés de regalo.' },
  { id: 'B-003', img: '2_Blends_tes_mixtos/Te_frutas_rojas.jpeg', cat: 'blends', name: 'Té de frutas rojas', sci: 'Blend botánico', desc: 'Blend rico en antocianinas y antioxidantes con base de frutos rojos. Sabor afrutado y perfil nutracéutico para líneas de tés funcionales y saludables.' },
  { id: 'B-004', img: '2_Blends_tes_mixtos/Te_jengibre_limon.jpeg', cat: 'blends', name: 'Té de jengibre con limón', sci: 'Blend botánico', desc: 'Combinación depurativa e inmunoestimulante de jengibre y limón. Ideal en formulaciones para sistemas inmune y depuración.' },
  { id: 'B-005', img: '2_Blends_tes_mixtos/Te_jengibre_naranja.jpeg', cat: 'blends', name: 'Té de jengibre con naranja', sci: 'Blend botánico', desc: 'Mezcla energizante y digestiva de jengibre y naranja. Perfil cítrico y especiado; ideal para tés matutinos y líneas de bienestar digestivo.' },
  { id: 'B-006', img: '2_Blends_tes_mixtos/Te_manzana_canela.jpeg', cat: 'blends', name: 'Té de manzana y canela', sci: 'Blend botánico', desc: 'Blend aromático y reconfortante con propiedades digestivas y antioxidantes. Sabor familiar y versátil; ideal para marcas propias y tés de temporada.' },
  { id: 'B-007', img: '2_Blends_tes_mixtos/Te_manzanilla_maracuya.jpeg', cat: 'blends', name: 'Té de manzanilla con maracuyá', sci: 'Blend botánico', desc: 'Blend calmante con la sinergia digestiva y ansiolítica de manzanilla y maracuyá. Ideal para tés de bienestar diario y marcas propias.' },
  { id: 'B-008', img: '2_Blends_tes_mixtos/Te_menopausia.jpeg', cat: 'blends', name: 'Té menopausia', sci: 'Blend funcional', desc: 'Blend formulado con plantas que alivian los síntomas de la menopausia: sofocos, insomnio e irritabilidad. Combinación de salvia, trébol rojo y otras hierbas de soporte hormonal femenino.' },
  { id: 'B-009', img: '2_Blends_tes_mixtos/Te_sueño_tranquilo.jpeg', cat: 'blends', name: 'Té sueño tranquilo', sci: 'Blend sedante', desc: 'Combinación de valeriana, passiflora, tilo y otras plantas sedantes para favorecer el sueño natural y la relajación profunda. Sin dependencia ni efectos secundarios.' },
  { id: 'B-010', img: '2_Blends_tes_mixtos/Te_TPM.jpeg', cat: 'blends', name: 'Té TPM (síndrome premenstrual)', sci: 'Blend funcional', desc: 'Mezcla de hierbas seleccionadas para el manejo de los síntomas del síndrome premenstrual: retención de líquidos, irritabilidad y dolor.' },
  { id: 'B-011', img: '2_Blends_tes_mixtos/Te_verde_jengibre.jpeg', cat: 'blends', name: 'Té verde con jengibre', sci: 'Blend funcional', desc: 'Sinergia antioxidante y termogénica del té verde con las propiedades digestivas y antiinflamatorias del jengibre. Popular en el segmento de control de peso y bienestar activo.' },
  { id: 'B-012', img: '2_Blends_tes_mixtos/Te_verde_naranja.jpeg', cat: 'blends', name: 'Té verde con naranja', sci: 'Blend funcional', desc: 'Blend refrescante y antioxidante de té verde con naranja. Perfil cítrico y funcional ideal para tés fríos, bebidas RTD y marcas propias de bienestar.' },
  { id: 'B-013', img: '2_Blends_tes_mixtos/Te_wellness.jpeg', cat: 'blends', name: 'Té wellness', sci: 'Blend adaptógeno', desc: 'Blend de hierbas adaptógenas y antioxidantes seleccionadas para promover el bienestar integral. Ideal para marcas propias de tés funcionales orientadas al mercado de salud.' },

  /* ─── ESPECIAS Y CONDIMENTOS ─── */
  { id: 'E-001', img: '3_Especias_Condimentos/Achiote.jpeg', cat: 'especias', name: 'Achiote', sci: 'Bixa orellana L.', desc: 'Semillas con bixina, uno de los colorantes naturales más utilizados en el mundo. Empleado en alimentos, cosmética y como fuente de betacarotenos en suplementos naturales.' },
  { id: 'E-002', img: '3_Especias_Condimentos/Ajedrea.jpeg', cat: 'especias', name: 'Ajedrea', sci: 'Satureja hortensis L.', desc: 'Hierba aromática con propiedades antimicrobianas y digestivas. Empleada en condimentos, tés herbales y formulaciones para el bienestar gastrointestinal.' },
  { id: 'E-003', img: '3_Especias_Condimentos/Ajo.jpeg', cat: 'especias', name: 'Ajo', sci: 'Allium sativum L.', desc: 'Especia con amplia evidencia en salud cardiovascular, acción antimicrobiana e inmunoestimulante. Base de suplementos cardiovasculares y condimento funcional en alimentación saludable.' },
  { id: 'E-004', img: '3_Especias_Condimentos/Albahaca.jpeg', cat: 'especias', name: 'Albahaca', sci: 'Ocimum basilicum L.', desc: 'Hierba aromática con propiedades antioxidantes, antiinflamatorias y adaptógenas. Ingrediente en condimentos funcionales, tés aromáticos y cosmética natural.' },
  { id: 'E-005', img: '3_Especias_Condimentos/Anis_estrellado.jpeg', cat: 'especias', name: 'Anís estrellado', sci: 'Illicium verum Hook. f.', desc: 'Especia con ácido shikímico, precursor de antivirales, y propiedades digestivas, expectorantes y aromáticas. Empleada en tés, licorería, cosmética y alimentación funcional.' },
  { id: 'E-006', img: '3_Especias_Condimentos/Azafran.jpeg', cat: 'especias', name: 'Azafrán', sci: 'Crocus sativus L.', desc: 'Especia de alto valor con propiedades antioxidantes y antidepresivas en investigación clínica. Ingrediente premium en alimentación gourmet, colorantes naturales y formulaciones nutracéuticas.' },
  { id: 'E-007', img: '3_Especias_Condimentos/Canela.jpeg', cat: 'especias', name: 'Canela (corteza)', sci: 'Cinnamomum cassia (L.) J. Presl', desc: 'Propiedades hipoglucemiantes, antioxidantes y antimicrobianas ampliamente documentadas. Ingrediente en suplementos metabólicos, tés y alimentos funcionales.' },
  { id: 'E-008', img: '3_Especias_Condimentos/Canela_Ceilan.jpeg', cat: 'especias', name: 'Canela de Ceilán', sci: 'Cinnamomum verum J. Presl', desc: 'Variedad premium con menor contenido en cumarina y mayor seguridad para consumo regular. Preferida para formulaciones de control glucémico y alimentación saludable de alta calidad.' },
  { id: 'E-009', img: '3_Especias_Condimentos/Cardamomo.jpeg', cat: 'especias', name: 'Cardamomo', sci: 'Elettaria cardamomum (L.) Maton', desc: 'Especia con propiedades digestivas, carminativas y aromáticas de alto valor sensorial. Empleada en mezclas de especias, tés, formulaciones digestivas y cosmética por su aroma exótico.' },
  { id: 'E-010', img: '3_Especias_Condimentos/Cebolla.jpeg', cat: 'especias', name: 'Cebolla', sci: 'Allium cepa L.', desc: 'Fuente de quercetina y compuestos organosulfurados con propiedades antioxidantes y cardiovasculares. Disponible en polvo para suplementos, alimentos funcionales y condimentos saludables.' },
  { id: 'E-011', img: '3_Especias_Condimentos/Cilantro.jpeg', cat: 'especias', name: 'Cilantro', sci: 'Coriandrum sativum L.', desc: 'Semilla aromática con propiedades digestivas y quelantes de metales pesados. Empleada en condimentos, infusiones digestivas y formulaciones para detox de metales pesados.' },
  { id: 'E-012', img: '3_Especias_Condimentos/Clavo_olor.jpeg', cat: 'especias', name: 'Clavo de olor', sci: 'Syzygium aromaticum (L.) Merr. & L.M. Perry', desc: 'Especia con el mayor contenido natural de eugenol, potente analgésico y antiséptico. Empleada en formulaciones para salud oral, digestión, cosmética y alimentación gourmet.' },
  { id: 'E-013', img: '3_Especias_Condimentos/Comino.jpeg', cat: 'especias', name: 'Comino', sci: 'Cuminum cyminum L.', desc: 'Especia con propiedades digestivas, carminativas y antimicrobianas bien documentadas. Ingrediente habitual en mezclas de especias, alimentos funcionales y formulaciones digestivas.' },
  { id: 'E-014', img: '3_Especias_Condimentos/Curcuma.jpeg', cat: 'especias', name: 'Cúrcuma', sci: 'Curcuma longa L.', desc: 'Raíz rica en curcumina, potente antiinflamatorio natural ampliamente estudiado. Ingrediente en suplementos antiinflamatorios, alimentos funcionales y colorantes naturales.' },
  { id: 'E-015', img: '3_Especias_Condimentos/Enebro.jpeg', cat: 'especias', name: 'Enebro', sci: 'Juniperus communis L.', desc: 'Baya con propiedades diuréticas, antisépticas y aromáticas de uso milenario. Ingrediente en bebidas espirituosas (ginebra), formulaciones para el soporte renal y condimentos de especialidad.' },
  { id: 'E-016', img: '3_Especias_Condimentos/Eneldo.jpeg', cat: 'especias', name: 'Eneldo', sci: 'Anethum graveolens L.', desc: 'Hierba aromática con propiedades digestivas, carminativas y galactogogas. Empleada en condimentos, tés digestivos y formulaciones para bienestar materno-infantil.' },
  { id: 'E-017', img: '3_Especias_Condimentos/Fenogreco.jpeg', cat: 'especias', name: 'Fenogreco', sci: 'Trigonella foenum-graecum L.', desc: 'Semillas con propiedades galactogogas, hipoglucemiantes y anabolizantes naturales. Empleadas en suplementos para lactancia, control glucémico y rendimiento deportivo.' },
  { id: 'E-018', img: '3_Especias_Condimentos/Hierba_dulce.jpeg', cat: 'especias', name: 'Hierba dulce (anís verde)', sci: 'Pimpinella anisum L.', desc: 'Especia con propiedades digestivas, expectorantes y aromatizantes de amplio uso. Ingrediente en digestivos, bebidas anisadas, tés y formulaciones para el bienestar gastrointestinal.' },
  { id: 'E-019', img: '3_Especias_Condimentos/Hinojo.jpeg', cat: 'especias', name: 'Hinojo', sci: 'Foeniculum vulgare Mill.', desc: 'Planta con propiedades digestivas, carminativas y estrogénicas suaves bien documentadas. Ingrediente en tés para digestión, cólicos infantiles y formulaciones de bienestar digestivo.' },
  { id: 'E-020', img: '3_Especias_Condimentos/Jengibre.jpeg', cat: 'especias', name: 'Jengibre', sci: 'Zingiber officinale Roscoe', desc: 'Rizoma con amplia evidencia clínica en control de náuseas, acción antiinflamatoria y termogénica. Ingrediente universal en tés, suplementos, alimentos funcionales y cosmética.' },
  { id: 'E-021', img: '3_Especias_Condimentos/Laurel.jpeg', cat: 'especias', name: 'Laurel', sci: 'Laurus nobilis L.', desc: 'Hoja aromática con propiedades digestivas, antifúngicas y aromáticas clásicas. Empleada en condimentos, tés digestivos y formulaciones herbales para el bienestar gastrointestinal.' },
  { id: 'E-022', img: '3_Especias_Condimentos/Mejorana.jpeg', cat: 'especias', name: 'Mejorana', sci: 'Origanum majorana L.', desc: 'Hierba con propiedades digestivas, antiespasmódicas y calmantes suaves. Empleada en condimentos, tés herbales y formulaciones para el bienestar digestivo y nervioso.' },
  { id: 'E-023', img: '3_Especias_Condimentos/Mostaza.jpeg', cat: 'especias', name: 'Mostaza (granos)', sci: 'Sinapis alba L.', desc: 'Semillas con propiedades estimulantes circulatorias y digestivas reconocidas. Disponibles en grano entero para condimentos, emulsiones y formulaciones rubefacientes de uso externo.' },
  { id: 'E-024', img: '3_Especias_Condimentos/Nuez_moscada.jpeg', cat: 'especias', name: 'Nuez moscada', sci: 'Myristica fragrans Houtt.', desc: 'Especia aromática con propiedades digestivas y carminativas de amplio uso. Empleada también en formulaciones herbales y cosméticas por su aceite esencial rico en miristicina y elemicina. Uso dentro de los rangos habituales de condimentación.' },
  { id: 'E-025', img: '3_Especias_Condimentos/Oregano.jpeg', cat: 'especias', name: 'Orégano', sci: 'Origanum vulgare L.', desc: 'Hierba con potente actividad antimicrobiana y antioxidante por su contenido en carvacrol y timol. Ingrediente en condimentos, suplementos antimicrobianos y productos de salud natural.' },
  { id: 'E-026', img: '3_Especias_Condimentos/Paprika_dulce.jpeg', cat: 'especias', name: 'Páprika dulce', sci: 'Capsicum annuum L.', desc: 'Pimiento rojo deshidratado con alto contenido en capsantina y antioxidantes naturales. Colorante natural y condimento empleado en alimentos funcionales, suplementos y cosmética.' },
  { id: 'E-027', img: '3_Especias_Condimentos/Paprika_picante.jpeg', cat: 'especias', name: 'Páprika picante', sci: 'Capsicum annuum L.', desc: 'Variedad picante de capsicum con mayor concentración de capsaicina y propiedades termogénicas y analgésicas. Ingrediente en condimentos, suplementos para el control de peso y formulaciones tópicas.' },
  { id: 'E-028', img: '3_Especias_Condimentos/Perejil.jpeg', cat: 'especias', name: 'Perejil', sci: 'Petroselinum crispum (Mill.) Fuss', desc: 'Hierba rica en vitamina C, apiol y clorofila con propiedades diuréticas y digestivas. Ingrediente en condimentos, suplementos nutricionales y formulaciones depurativas.' },
  { id: 'E-029', img: '3_Especias_Condimentos/Pimienta_blanca.jpeg', cat: 'especias', name: 'Pimienta blanca', sci: 'Piper nigrum L.', desc: 'Versión madura y pelada de la pimienta negra con sabor más delicado y refinado. Empleada en condimentos premium, mezclas de especias y formulaciones digestivas.' },
  { id: 'E-030', img: '3_Especias_Condimentos/Pimienta_calabresa.jpeg', cat: 'especias', name: 'Pimienta calabresa', sci: 'Capsicum annuum L.', desc: 'Pimiento rojo seco con sabor levemente picante y aroma característico. Condimento versátil para alimentos funcionales y mezclas de especias gourmet.' },
  { id: 'E-031', img: '3_Especias_Condimentos/Pimienta_Cayena.jpeg', cat: 'especias', name: 'Pimienta de Cayena', sci: 'Capsicum annuum L.', desc: 'Pimienta con alto contenido en capsaicina y propiedades termogénicas y analgésicas validadas clínicamente. Base de suplementos para control de peso, dolor y mejora de la circulación.' },
  { id: 'E-032', img: '3_Especias_Condimentos/Pimienta_jamaicana.jpeg', cat: 'especias', name: 'Pimienta jamaicana', sci: 'Pimenta dioica (L.) Merr.', desc: 'Especia con perfil de sabor complejo que evoca clavo, canela y nuez moscada simultáneamente. Empleada en condimentos gourmet, marinados y formulaciones de especialidad.' },
  { id: 'E-033', img: '3_Especias_Condimentos/Pimienta_negra.jpeg', cat: 'especias', name: 'Pimienta negra (granos)', sci: 'Piper nigrum L.', desc: 'Rica en piperina, que potencia la biodisponibilidad de otros nutrientes, especialmente curcumina. Ingrediente esencial en condimentos y suplementos.' },
  { id: 'E-034', img: '3_Especias_Condimentos/Pimienta_rosa.jpeg', cat: 'especias', name: 'Pimienta rosa', sci: 'Schinus terebinthifolius Raddi.', desc: 'Fruto de aroeira con notas aromáticas suaves y levemente picantes de alta valoración gastronómica. Apreciado en gastronomía gourmet, mezclas de especias premium y cosmética.' },
  { id: 'E-035', img: '3_Especias_Condimentos/Romero.jpeg', cat: 'especias', name: 'Romero', sci: 'Salvia rosmarinus Spenn.', desc: 'Hierba aromática con propiedades antioxidantes, estimulantes circulatorias y neuroprotectoras. Empleada en alimentos funcionales, cosmética natural y formulaciones herbales de bienestar.' },
  { id: 'E-036', img: '3_Especias_Condimentos/Salvia.jpeg', cat: 'especias', name: 'Salvia', sci: 'Salvia officinalis L.', desc: 'Hierba aromática con propiedades antisépticas, antiinflamatorias y para el control de la sudoración. Ingrediente en condimentos herbales, suplementos y formulaciones para menopausia.' },
  { id: 'E-037', img: '3_Especias_Condimentos/Tomillo.jpeg', cat: 'especias', name: 'Tomillo', sci: 'Thymus vulgaris L.', desc: 'Planta rica en timol con potentes propiedades antisépticas, expectorantes y antimicrobianas. Ingrediente en formulaciones respiratorias, higiene oral y condimentos funcionales.' },

  /* ─── EXTRACTOS ─── */
  { id: 'X-001', img: '4_Extractos/Açai_extracto.jpeg', cat: 'extractos', name: 'Açaí extracto 10%', sci: 'Euterpe oleracea Mart.', desc: 'Extracto estandarizado al 10% de antocianinas con alta capacidad antioxidante. Ingrediente premium en suplementos antienvejecimiento, energizantes y formulaciones de belleza desde adentro.' },
  { id: 'X-002', img: '4_Extractos/Acerola_extracto.jpeg', cat: 'extractos', name: 'Acerola extracto', sci: 'Malpighia emarginata DC.', desc: 'Extracto concentrado con alta concentración de vitamina C natural. Ingrediente clave en suplementos inmunitarios, antioxidantes y formulaciones de belleza.' },
  { id: 'X-003', img: '4_Extractos/Acerola_extracto_17.jpeg', cat: 'extractos', name: 'Acerola extracto 17%', sci: 'Malpighia emarginata DC.', desc: 'Extracto estandarizado al 17% de vitamina C natural con alta trazabilidad. Para formulaciones nutracéuticas premium que requieren aporte certificado de vitamina C de origen botánico.' },
  { id: 'X-004', img: '4_Extractos/Alcachofa_extracto.jpeg', cat: 'extractos', name: 'Alcachofa extracto', sci: 'Cynara scolymus L.', desc: 'Extracto con cinarina estandarizada para soporte hepático y control del colesterol. Ingrediente de referencia en suplementos hepáticos y formulaciones para el metabolismo lipídico.' },
  { id: 'X-005', img: '4_Extractos/Arándano_rojo.jpeg', cat: 'extractos', name: 'Arándano rojo (extracto)', sci: 'Vaccinium macrocarpon Aiton', desc: 'Extracto con proantocianidinas para la prevención de infecciones urinarias recurrentes. Ingrediente de referencia en suplementos para salud urinaria con amplia evidencia clínica.' },
  { id: 'X-006', img: '4_Extractos/Berenjena_extracto.jpeg', cat: 'extractos', name: 'Berenjena extracto', sci: 'Solanum melongena L.', desc: 'Extracto con nasunina y compuestos hipocolesterolemiantes y antioxidantes. Empleado en suplementos para el control del colesterol y bienestar cardiovascular.' },
  { id: 'X-007', img: '4_Extractos/Boldo_extracto.jpeg', cat: 'extractos', name: 'Boldo extracto', sci: 'Peumus boldus Molina', desc: 'Extracto con boldina estandarizada para soporte biliar y hepático de alta eficacia. Versión concentrada del boldo para formulaciones de mayor potencia y biodisponibilidad.' },
  { id: 'X-008', img: '4_Extractos/Camu_camu_extracto.jpeg', cat: 'extractos', name: 'Camu camu extracto', sci: 'Myrciaria dubia (Kunth) McVaugh', desc: 'Extracto con la mayor concentración conocida de vitamina C natural. Ingrediente premium en suplementos inmunitarios y antioxidantes de alta gama.' },
  { id: 'X-009', img: '4_Extractos/Canela_de_viejo.jpeg', cat: 'extractos', name: 'Canela de viejo (extracto)', sci: 'Ocotea odorifera (Vell.) Rohwer', desc: 'Extracto concentrado con mayor actividad antiinflamatoria y analgésica que la planta entera. Para formulaciones articulares y reumáticas de alta potencia y biodisponibilidad.' },
  { id: 'X-010', img: '4_Extractos/Carqueja_extracto.jpeg', cat: 'extractos', name: 'Carqueja extracto', sci: 'Baccharis trimera (Less.) DC.', desc: 'Extracto con principios activos digestivos y hepatoprotectores en alta concentración. Para formulaciones de soporte hepático y digestivo de mayor biodisponibilidad.' },
  { id: 'X-011', img: '4_Extractos/Catuaba_extracto.jpeg', cat: 'extractos', name: 'Catuaba extracto', sci: 'Erythroxylum catuaba Arr. Cam.', desc: 'Extracto con alcaloides y flavonoides en concentración elevada. Mayor potencia para formulaciones de vitalidad sexual y soporte del sistema nervioso respecto a la planta entera.' },
  { id: 'X-012', img: '4_Extractos/Centella_asiática.jpeg', cat: 'extractos', name: 'Centella asiática extracto', sci: 'Centella asiatica (L.) Urb.', desc: 'Extracto estandarizado en asiaticósidos para formulaciones cosméticas y nutracéuticas de alta eficacia. Referencia en tratamientos para celulitis, cicatrices y mejora de la circulación.' },
  { id: 'X-013', img: '4_Extractos/Cola_de_caballo.jpeg', cat: 'extractos', name: 'Cola de caballo extracto', sci: 'Equisetum arvense L.', desc: 'Extracto con sílice orgánico estandarizado para máxima absorción y biodisponibilidad. Ingrediente premium en suplementos para cabello, piel, uñas y tejido conectivo.' },
  { id: 'X-014', img: '4_Extractos/Detox_rojo.jpeg', cat: 'extractos', name: 'Detox rojo soluble en polvo', sci: 'Blend de extractos', desc: 'Blend de extractos de frutos rojos con alta actividad antioxidante y depurativa. Ingrediente funcional listo para usar en bebidas RTD, suplementos y productos de marca propia.' },
  { id: 'X-015', img: '4_Extractos/Detox_verde.jpeg', cat: 'extractos', name: 'Detox verde soluble en polvo', sci: 'Blend de extractos', desc: 'Mezcla funcional de extractos verdes con acción depurativa y antioxidante. Ingrediente listo para usar en bebidas detox, suplementos y alimentos funcionales de marca propia.' },
  { id: 'X-016', img: '4_Extractos/Espinheira_santa.jpeg', cat: 'extractos', name: 'Espinheira santa (extracto)', sci: 'Maytenus ilicifolia Mart. ex Reissek', desc: 'Extracto con maytenina y principios gastroprotectores en alta concentración. Para formulaciones antiulcerosas y para gastritis de alta potencia y biodisponibilidad.' },
  { id: 'X-017', img: '4_Extractos/Fenogreco.jpeg', cat: 'extractos', name: 'Fenogreco extracto', sci: 'Trigonella foenum-graecum L.', desc: 'Extracto estandarizado en saponinas con propiedades galactogogas, anabolizantes y para control glucémico. Para formulaciones especializadas de alta concentración y precisión de dosis.' },
  { id: 'X-018', img: '4_Extractos/Goji_berry.jpeg', cat: 'extractos', name: 'Goji berry (extracto)', sci: 'Lycium barbarum L.', desc: 'Extracto de wolfberry con zeaxantina, polisacáridos y antioxidantes concentrados. Ingrediente premium en suplementos para la salud visual, inmunidad y antienvejecimiento.' },
  { id: 'X-019', img: '4_Extractos/Griffonia_simplicifolia.jpeg', cat: 'extractos', name: 'Griffonia simplicifolia extracto', sci: 'Griffonia simplicifolia (DC.) Baill.', desc: 'Extracto estandarizado en 5-HTP, precursor natural de la serotonina. Ingrediente en suplementos para el estado de ánimo, control del apetito, sueño y bienestar emocional.' },
  { id: 'X-020', img: '4_Extractos/Guaraná_extracto.jpeg', cat: 'extractos', name: 'Guaraná extracto', sci: 'Paullinia cupana Kunth', desc: 'Extracto concentrado de guaraná con cafeína natural estandarizada. Para formulaciones energizantes y termogénicas de mayor potencia y biodisponibilidad.' },
  { id: 'X-021', img: '4_Extractos/Guaraná_extracto_10.jpeg', cat: 'extractos', name: 'Guaraná extracto 10%', sci: 'Paullinia cupana Kunth', desc: 'Extracto estandarizado al 10% de cafeína natural para formulaciones con dosificación precisa. Ingrediente de referencia en suplementos energizantes y de rendimiento deportivo.' },
  { id: 'X-022', img: '4_Extractos/Guaraná_extracto_22.jpeg', cat: 'extractos', name: 'Guaraná extracto 22%', sci: 'Paullinia cupana Kunth', desc: 'Extracto de alta potencia al 22% de cafeína natural. Para formulaciones premium de energía y rendimiento donde se requiere la mayor concentración de cafeína natural disponible.' },
  { id: 'X-023', img: '4_Extractos/Hibiscus_extracto.jpeg', cat: 'extractos', name: 'Hibiscus extracto', sci: 'Hibiscus sabdariffa L.', desc: 'Extracto estandarizado en antocianinas con propiedades antihipertensivas y antioxidantes. Para formulaciones cardiovasculares y de control de presión arterial de alta biodisponibilidad.' },
  { id: 'X-024', img: '4_Extractos/Lapacho_morado.jpeg', cat: 'extractos', name: 'Lapacho morado (extracto)', sci: 'Handroanthus impetiginosus (Mart. ex DC.) Mattos', desc: 'Extracto con lapachol y beta-lapachona en alta concentración con propiedades antifúngicas e inmunomoduladoras. Para formulaciones especializadas de soporte inmunológico y antifúngico.' },
  { id: 'X-025', img: '4_Extractos/Manzanilla_extracto.jpeg', cat: 'extractos', name: 'Manzanilla extracto', sci: 'Matricaria chamomilla L.', desc: 'Extracto estandarizado en apigenina con potente acción antiinflamatoria, ansiolítica y digestiva. Para formulaciones nutracéuticas y cosméticas de alta eficacia clínica.' },
  { id: 'X-026', img: '4_Extractos/Mate_verde.jpeg', cat: 'extractos', name: 'Mate verde extracto', sci: 'Ilex paraguariensis A.St.-Hil.', desc: 'Extracto con cafeína, polifenoles y xantinas concentradas. Para formulaciones energizantes y termogénicas.' },
  { id: 'X-027', img: '4_Extractos/Muirapuama.jpeg', cat: 'extractos', name: 'Muirapuama (extracto)', sci: 'Ptychopetalum olacoides Benth.', desc: 'Extracto concentrado de muirapuama con mayor potencia en propiedades afrodisíacas y tónicas nerviosas. Para formulaciones de vitalidad sexual premium de alta biodisponibilidad.' },
  { id: 'X-028', img: '4_Extractos/Naranja_amarga.jpeg', cat: 'extractos', name: 'Naranja amarga (extracto)', sci: 'Citrus aurantium L.', desc: 'Extracto estandarizado en sinefrina para termogénesis y quema de grasa. Base de suplementos para control de peso y rendimiento deportivo como alternativa a la efedrina.' },
  { id: 'X-029', img: '4_Extractos/Olivo.jpeg', cat: 'extractos', name: 'Olivo extracto', sci: 'Olea europaea L.', desc: 'Extracto estandarizado en oleuropeína para máxima actividad antihipertensiva y antioxidante. Ingrediente de referencia en suplementos cardiovasculares de alta gama.' },
  { id: 'X-030', img: '4_Extractos/Ora_pro_nóbis.jpeg', cat: 'extractos', name: 'Ora pro nóbis (polvo soluble)', sci: 'Pereskia aculeata Mill.', desc: 'Polvo soluble con alto contenido proteico y mucílagos bioactivos de pereskia. Para suplementos proteicos vegetales, alimentos funcionales y formulaciones nutricionales innovadoras.' },
  { id: 'X-031', img: '4_Extractos/Pfaffia.jpeg', cat: 'extractos', name: 'Pfaffia (extracto)', sci: 'Pfaffia paniculata (Mart.) Kuntze', desc: 'Extracto con beta-ecdisterona y sitosteroles en alta concentración. Para formulaciones adaptógenas, energizantes y de rendimiento deportivo premium.' },
  { id: 'X-032', img: '4_Extractos/Propóleo.jpeg', cat: 'extractos', name: 'Propóleo (extracto)', sci: 'Apis mellifera', desc: 'Extracto de propóleo con flavonoides y ácidos fenólicos antimicrobianos concentrados. Ingrediente en suplementos inmunitarios, productos de salud oral y formulaciones antibacterianas naturales.' },
  { id: 'X-033', img: '4_Extractos/Remolacha.jpeg', cat: 'extractos', name: 'Remolacha deshidratada soluble', sci: 'Beta vulgaris L.', desc: 'Polvo soluble con alto contenido en betalaínas y nitratos con propiedades vasodilatadoras y antioxidantes. Ingrediente en bebidas deportivas pre-entreno, suplementos y alimentos funcionales.' },
  { id: 'X-034', img: '4_Extractos/Saw_palmetto.jpeg', cat: 'extractos', name: 'Saw palmetto extracto', sci: 'Serenoa repens (Bartram) Small', desc: 'Extracto estandarizado en ácidos grasos y fitosteroles con máxima actividad para soporte prostático. Ingrediente de referencia en suplementos para salud masculina.' },
  { id: 'X-035', img: '4_Extractos/Sena.jpeg', cat: 'extractos', name: 'Sena extracto', sci: 'Senna alexandrina Mill.', desc: 'Extracto con senósidos estandarizados para acción laxante precisa y reproducible. Para formulaciones farmacéuticas y nutracéuticas de alta calidad y control de proceso.' },
  { id: 'X-036', img: '4_Extractos/Te_de_bugre.jpeg', cat: 'extractos', name: 'Té de bugre (extracto)', sci: 'Cordia ecalyculata Vell.', desc: 'Extracto concentrado con mayor actividad diurética y para control de peso. Para formulaciones termogénicas y de adelgazamiento de mayor potencia que la planta entera.' },
  { id: 'X-037', img: '4_Extractos/Te_bugre_rojo.jpeg', cat: 'extractos', name: 'Té de bugre rojo (extracto)', sci: 'Cordia ecalyculata Vell.', desc: 'Variedad roxo del té de bugre en extracto con perfil fitoquímico diferenciado. Para formulaciones especializadas en control de peso y salud cardiovascular.' },
  { id: 'X-038', img: '4_Extractos/Te_verde.jpeg', cat: 'extractos', name: 'Té verde (extracto)', sci: 'Camellia sinensis (L.) Kuntze', desc: 'Extracto estandarizado en EGCG para formulaciones antioxidantes y termogénicas de alta potencia. Ingrediente clave en suplementos de control de peso y antienvejecimiento.' },
  { id: 'X-039', img: '4_Extractos/Tribulus_extracto.jpeg', cat: 'extractos', name: 'Tribulus extracto 40%', sci: 'Tribulus terrestris L.', desc: 'Extracto estandarizado al 40% de saponinas con propiedades para soporte hormonal masculino y rendimiento deportivo. Ingrediente premium en suplementos especializados para hombres.' },
  { id: 'X-040', img: '4_Extractos/Uña_de_gato.jpeg', cat: 'extractos', name: 'Uña de gato extracto seco', sci: 'Uncaria tomentosa (Willd.) DC.', desc: 'Extracto seco con alcaloides oxindólicos estandarizados de alta pureza. Máxima actividad inmunomoduladora y antiinflamatoria para formulaciones nutracéuticas y oncológicas complementarias.' },

  /* ─── FRUTAS Y VEGETALES EN POLVO ─── */
  { id: 'F-001', img: '5_Frutas_vegetales_en_polvo/Batata_dulce.jpeg', cat: 'frutas', name: 'Batata dulce', sci: 'Ipomoea batatas (L.) Lam.', desc: 'Polvo de camote deshidratado rico en betacarotenos, antioxidantes y carbohidratos complejos de bajo índice glucémico. Ingrediente en alimentos funcionales, suplementos deportivos y mezclas nutricionales.' },
  { id: 'F-002', img: '5_Frutas_vegetales_en_polvo/Berenjena.jpeg', cat: 'frutas', name: 'Berenjena', sci: 'Solanum melongena L.', desc: 'Polvo de berenjena deshidratada con nasunina y compuestos hipocolesterolemiantes. Ingrediente en suplementos para el colesterol y alimentos funcionales de bajo índice glucémico.' },
  { id: 'F-003', img: '5_Frutas_vegetales_en_polvo/Cebolla.jpeg', cat: 'frutas', name: 'Cebolla', sci: 'Allium cepa L.', desc: 'Polvo de cebolla deshidratada con quercetina y compuestos organosulfurados bioactivos. Ingrediente funcional en condimentos, suplementos y formulaciones para salud cardiovascular.' },
  { id: 'F-004', img: '5_Frutas_vegetales_en_polvo/Fresa.jpeg', cat: 'frutas', name: 'Fresa (polvo)', sci: 'Fragaria × ananassa Duchesne', desc: 'Polvo de fresa deshidratada con antocianinas y vitamina C en formato práctico. Para bebidas funcionales, suplementos y formulaciones donde se requiere practicidad y sabor natural.' },
  { id: 'F-005', img: '5_Frutas_vegetales_en_polvo/Goji_berry.jpeg', cat: 'frutas', name: 'Goji berry', sci: 'Lycium barbarum L.', desc: 'Polvo de wolfberry deshidratado con zeaxantina, polisacáridos y vitaminas concentradas. Ingrediente premium en suplementos antioxidantes, antienvejecimiento y alimentos funcionales.' },
  { id: 'F-006', img: '5_Frutas_vegetales_en_polvo/Harina_de_maracuyá.jpeg', cat: 'frutas', name: 'Harina de maracuyá', sci: 'Passiflora edulis Sims', desc: 'Harina de cáscara y semillas de maracuyá rica en pectina y fibra soluble. Ingrediente en suplementos para el control glucémico, colesterol y bienestar intestinal.' },
  { id: 'F-007', img: '5_Frutas_vegetales_en_polvo/Harina_plátano_verde.jpeg', cat: 'frutas', name: 'Harina de plátano verde', sci: 'Musa × paradisiaca L.', desc: 'Harina de banana verde rica en almidón resistente y potasio. Prebiótico natural para formulaciones de salud intestinal, suplementos y alimentos funcionales innovadores.' },
  { id: 'F-008', img: '5_Frutas_vegetales_en_polvo/Harina_de_uva.jpeg', cat: 'frutas', name: 'Harina de uva', sci: 'Vitis vinifera L.', desc: 'Harina del orujo de uva con resveratrol, OPC y fibra de alto valor antioxidante. Ingrediente en suplementos, alimentos funcionales y formulaciones para salud cardiovascular.' },
  { id: 'F-009', img: '5_Frutas_vegetales_en_polvo/Hierba_dulce.jpeg', cat: 'frutas', name: 'Hierba dulce (anís verde) en polvo', sci: 'Pimpinella anisum L.', desc: 'Anís en polvo con propiedades digestivas y saborizantes naturales. Ingrediente en mezclas de especias, formulaciones digestivas y saborizantes naturales para alimentos.' },
  { id: 'F-010', img: '5_Frutas_vegetales_en_polvo/Manzana.jpeg', cat: 'frutas', name: 'Manzana', sci: 'Malus domestica Borkh.', desc: 'Polvo de manzana deshidratada con pectina, quercetina y vitamina C. Ingrediente natural en suplementos, alimentos funcionales y saborizantes de origen botánico.' },
  { id: 'F-011', img: '5_Frutas_vegetales_en_polvo/Remolacha.jpeg', cat: 'frutas', name: 'Remolacha', sci: 'Beta vulgaris L.', desc: 'Polvo rico en betalaínas, nitratos y antioxidantes con propiedades vasodilatadoras. Muy empleado en bebidas deportivas pre-entreno, suplementos y alimentos funcionales.' },
  { id: 'F-012', img: '5_Frutas_vegetales_en_polvo/Zanahoria.jpeg', cat: 'frutas', name: 'Zanahoria', sci: 'Daucus carota L.', desc: 'Polvo de zanahoria con alto contenido en betacarotenos y antioxidantes naturales. Ingrediente en suplementos para la piel, la visión y alimentos funcionales.' },

  /* ─── ORGÁNICOS ─── */
  { id: 'O-001', img: '6_Organicos/Açai_organico.jpeg', cat: 'organicos', name: 'Açaí orgánico (polvo soluble)', sci: 'Euterpe oleracea Mart.', desc: 'Açaí certificado orgánico en polvo soluble con máxima concentración de antocianinas. Ingrediente premium para marcas con enfoque en productos orgánicos, antioxidantes y sostenibles.' },
  { id: 'O-002', img: '6_Organicos/Camu_camu_orgánico.jpeg', cat: 'organicos', name: 'Camu camu orgánico (extracto seco)', sci: 'Myrciaria dubia (Kunth) McVaugh', desc: 'Extracto orgánico certificado con la mayor concentración de vitamina C natural. Para formulaciones inmunitarias premium con certificación orgánica y trazabilidad completa.' },
  { id: 'O-003', img: '6_Organicos/Guaraná_orgánico.jpeg', cat: 'organicos', name: 'Guaraná orgánico', sci: 'Paullinia cupana Kunth', desc: 'Guaraná cultivado sin agroquímicos con cafeína natural certificada. Para formulaciones energizantes y termogénicas premium dirigidas al segmento orgánico y de consumo responsable.' },
  { id: 'O-004', img: '6_Organicos/Yerba_mate.jpeg', cat: 'organicos', name: 'Yerba mate orgánica', sci: 'Ilex paraguariensis A.St.-Hil.', desc: 'Yerba mate certificada orgánica, libre de agroquímicos. Para marcas de tés y bebidas funcionales orientadas al mercado orgánico, sostenible y de comercio justo.' },

  /* ─── OTROS ─── */
  { id: 'P-001', img: '7_Otros/Arginina.jpeg', cat: 'otros', name: 'Arginina', sci: 'Aminoácido semiesencial', desc: 'Aminoácido semiesencial con propiedades vasodilatadoras y estimulante de la síntesis de óxido nítrico. Ingrediente en suplementos para rendimiento deportivo, circulación y salud sexual masculina.' },
  { id: 'P-002', img: '7_Otros/Ashwagandha.jpeg', cat: 'otros', name: 'Ashwagandha', sci: 'Withania somnifera (L.) Dunal', desc: 'Adaptógeno con amplia evidencia clínica en reducción del cortisol, manejo del estrés y rendimiento físico e intelectual. Ingrediente en suplementos para bienestar mental y físico.' },
  { id: 'P-003', img: '7_Otros/Calcio_de_ostras.jpeg', cat: 'otros', name: 'Calcio de ostras en polvo', sci: 'Fuente mineral natural', desc: 'Fuente de calcio con alta biodisponibilidad natural. Ingrediente en suplementos de calcio natural, formulaciones para huesos y dientes y nutracéuticos.' },
  { id: 'P-004', img: '7_Otros/Caparazón_de_crustáceo.jpeg', cat: 'otros', name: 'Caparazón de crustáceo', sci: 'Fuente de quitina', desc: 'Fuente de quitina y glucosamina con alta pureza. Ingrediente en suplementos para la salud articular y como materia prima para la producción de quitosano.' },
  { id: 'P-005', img: '7_Otros/Chía.jpeg', cat: 'otros', name: 'Chía', sci: 'Salvia hispanica L.', desc: 'Semilla con alto contenido de omega-3 (ALA), fibra soluble y proteína completa de alta digestibilidad. Ingrediente en superalimentos, suplementos y alimentos funcionales.' },
  { id: 'P-006', img: '7_Otros/Clorela.jpeg', cat: 'otros', name: 'Clorela', sci: 'Chlorella vulgaris Beyerinck', desc: 'Microalga con alta concentración en clorofila, proteínas completas y vitaminas del grupo B. Ingrediente en suplementos detox, nutricionales y formulaciones para quelación de metales pesados.' },
  { id: 'P-007', img: '7_Otros/Colágeno.jpeg', cat: 'otros', name: 'Colágeno', sci: 'Proteína estructural', desc: 'Proteína estructural esencial para piel, articulaciones y huesos. Empleada en suplementos de belleza, rendimiento deportivo y longevidad activa.' },
  { id: 'P-008', img: '7_Otros/Dolomita.jpeg', cat: 'otros', name: 'Dolomita', sci: 'Fuente mineral natural', desc: 'Fuente mineral de calcio y magnesio en proporción equilibrada y de origen natural. Ingrediente en suplementos de remineralización ósea y formulaciones para el equilibrio mineral del organismo.' },
  { id: 'P-009', img: '7_Otros/Espirulina.jpeg', cat: 'otros', name: 'Espirulina', sci: 'Arthrospira platensis (Nordstedt) Gomont', desc: 'Microalga con alto contenido en proteínas de alta biodisponibilidad, vitaminas, minerales y clorofila. Ingrediente en suplementos nutricionales y detox.' },
  { id: 'P-010', img: '7_Otros/Glucomannan.jpeg', cat: 'otros', name: 'Glucomannan', sci: 'Amorphophallus konjac K. Koch', desc: 'Fibra soluble con alta viscosidad y evidencia clínica para el control de glucosa, colesterol y apetito. Ingrediente en suplementos para el control de peso.' },
  { id: 'P-011', img: '7_Otros/Levadura_de_cerveza.jpeg', cat: 'otros', name: 'Levadura de cerveza', sci: 'Saccharomyces cerevisiae Meyen ex E.C. Hansen', desc: 'Rica en vitaminas del grupo B, aminoácidos esenciales, cromo y zinc de alta biodisponibilidad. Ingrediente nutricional en suplementos para piel, cabello, energía y equilibrio glucémico.' },
  { id: 'P-012', img: '7_Otros/Linaza_semilla.jpeg', cat: 'otros', name: 'Linaza (semilla)', sci: 'Linum usitatissimum L.', desc: 'Semilla con omega-3 (ALA), lignanos y fibra soluble de probado valor nutricional. Ingrediente versátil en suplementos cardiovasculares, digestivos, hormonales y alimentos funcionales.' },
  { id: 'P-013', img: '7_Otros/Linaza_dorada.jpeg', cat: 'otros', name: 'Linaza dorada', sci: 'Linum usitatissimum L.', desc: 'Variedad premium de linaza con mayor contenido en lignanos y omega-3. Para suplementos hormonales femeninos, formulaciones cardiovasculares y de bienestar digestivo de alta calidad.' },
  { id: 'P-014', img: '7_Otros/Maca_peruana.jpeg', cat: 'otros', name: 'Maca peruana', sci: 'Lepidium meyenii Walp.', desc: 'Raíz adaptógena con propiedades para energía, fertilidad y equilibrio hormonal. Empleada en suplementos para vitalidad y bienestar hormonal.' },
  { id: 'P-015', img: '7_Otros/Maca_peruana_negra.jpeg', cat: 'otros', name: 'Maca peruana negra', sci: 'Lepidium meyenii Walp.', desc: 'Variedad negra de maca con mayor concentración de glucosinolatos bioactivos. Asociada especialmente al rendimiento cognitivo, fertilidad masculina y soporte de la memoria.' },
  { id: 'P-016', img: '7_Otros/Maca_peruana_roja.jpeg', cat: 'otros', name: 'Maca peruana roja', sci: 'Lepidium meyenii Walp.', desc: 'Variedad roja de maca con mayor concentración de antocianinas. Asociada al soporte hormonal femenino, bienestar óseo y soporte prostático en hombres.' },
  { id: 'P-017', img: '7_Otros/Proteína_de_arroz.jpeg', cat: 'otros', name: 'Proteína de arroz', sci: 'Oryza sativa L.', desc: 'Proteína vegetal hipoalergénica de alta digestibilidad y perfil de aminoácidos completo. Ingrediente en suplementos proteicos veganos, deportivos y formulaciones libres de gluten y lácteos.' },
  { id: 'P-018', img: '7_Otros/Proteína_de_guisante.jpeg', cat: 'otros', name: 'Proteína de guisante', sci: 'Pisum sativum L.', desc: 'Proteína vegetal con perfil completo de aminoácidos esenciales, alta palatabilidad y baja alergenicidad. Empleada en suplementos proteicos veganos y deportivos.' },
  { id: 'P-019', img: '7_Otros/Psyllium.jpeg', cat: 'otros', name: 'Psyllium', sci: 'Plantago ovata Forssk.', desc: 'Cáscara de semilla con altísima concentración de fibra soluble. Con evidencia clínica para control glucémico, colesterol y regularidad intestinal.' },
];

/* ═══════════════════════════════════════════
   RENDER ENGINE — productos.html
═══════════════════════════════════════════ */

let activeCat = 'all';
let searchQuery = '';

const grid = document.getElementById('prodGrid');
const emptyEl = document.getElementById('prodEmpty');
const searchIn = document.getElementById('searchInput');
const clearBtn = document.getElementById('clearBtn');
const countLbl = document.getElementById('countLabel');
const fcBtns = document.querySelectorAll('.fc-btn');

function buildCard(p, delay) {
  const cat = CATS[p.cat];
  const el = document.createElement('div');
  el.className = `prod-card theme-${p.cat}${p.warning ? ' prod-card--warn' : ''}`;
  el.style.animationDelay = `${Math.min(delay, 28) * 45}ms`;
  el.setAttribute('role', 'button');
  el.setAttribute('tabindex', '0');
  el.setAttribute('aria-label', `Ver detalles: ${p.name}`);

  const imgSrc = p.img
    ? `img/3_Productos/${p.img}`
    : `img/3_Productos/${cat.fallback}`;

  el.innerHTML = `
    <div class="pc-inner">
      <div class="pc-front">
        <div class="pc-top">
          <div class="pc-scan" aria-hidden="true"></div>
          <div class="pc-corners" aria-hidden="true">
            <span class="cc-tl"></span><span class="cc-tr"></span>
            <span class="cc-bl"></span><span class="cc-br"></span>
          </div>
          <div class="pc-meta">
            <span class="pc-id">${p.id}</span>
            <span class="pc-badge">${cat.label}</span>
          </div>
          <div class="pc-img-wrap">
            <img src="${imgSrc}" alt="${p.name}" loading="lazy"
              onerror="this.style.display='none';this.nextElementSibling.style.display='flex'">
            <div class="pc-emoji-fallback" style="display:none">${cat.emoji}</div>
          </div>
        </div>
        <div class="pc-bottom">
          <p class="pc-name">${p.name}</p>
          <p class="pc-sci">${p.sci}</p>
          <p class="pc-hint">[ hover para ver descripción ]</p>
        </div>
      </div>
      <div class="pc-back">
        <span class="pb-chip">${p.warning ? '⚠️ AVISO REG.' : cat.label}</span>
        <h3 class="pb-name">${p.name}</h3>
        <p class="pb-desc">${p.desc}</p>
        <div class="pb-divider"></div>
        <p class="pb-sci">${p.sci}</p>
        <p class="pb-id">${p.id}</p>
      </div>
    </div>`;

  el.addEventListener('click', () => el.classList.toggle('flipped'));
  el.addEventListener('keydown', e => {
    if (e.key === 'Enter' || e.key === ' ') { e.preventDefault(); el.classList.toggle('flipped'); }
  });
  return el;
}

function render() {
  const q = searchQuery.toLowerCase().trim();

  const filtered = products.filter(p => {
    const matchCat = activeCat === 'all' || p.cat === activeCat;
    const matchSearch = !q
      || p.name.toLowerCase().includes(q)
      || p.sci.toLowerCase().includes(q)
      || p.id.toLowerCase().includes(q)
      || p.desc.toLowerCase().includes(q);
    return matchCat && matchSearch;
  });

  grid.innerHTML = '';
  countLbl.textContent = `${filtered.length} producto${filtered.length !== 1 ? 's' : ''}`;

  if (!filtered.length) {
    emptyEl.removeAttribute('hidden');
    return;
  }
  emptyEl.setAttribute('hidden', '');

  const frag = document.createDocumentFragment();
  filtered.forEach((p, i) => frag.appendChild(buildCard(p, i)));
  grid.appendChild(frag);
}

/* ── Search ── */
searchIn.addEventListener('input', () => {
  searchQuery = searchIn.value;
  clearBtn.classList.toggle('visible', searchQuery.length > 0);
  render();
});
clearBtn.addEventListener('click', () => {
  searchIn.value = ''; searchQuery = '';
  clearBtn.classList.remove('visible');
  searchIn.focus(); render();
});

/* ── Category filters ── */
fcBtns.forEach(btn => btn.addEventListener('click', () => {
  fcBtns.forEach(b => b.classList.remove('active'));
  btn.classList.add('active');
  activeCat = btn.dataset.cat;
  render();
}));

/* ── Init ── */
render();